//! Core types for the script session layer.

use std::fmt;

/// Opaque reference to a JavaScript object wrapper.
///
/// Each `JsObjectRef` uniquely identifies a (Entity, [`ComponentKind`]) pair
/// within an [`IdentityMap`](crate::IdentityMap). The raw `u64` value is
/// generated by the identity map's internal counter.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct JsObjectRef(u64);

impl JsObjectRef {
    /// Create a `JsObjectRef` from a raw `u64`.
    #[must_use]
    pub fn from_raw(raw: u64) -> Self {
        Self(raw)
    }

    /// Extract the raw `u64` value.
    #[must_use]
    pub fn to_raw(self) -> u64 {
        self.0
    }
}

impl fmt::Display for JsObjectRef {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "JsObjectRef({})", self.0)
    }
}

/// The kind of DOM component a JS wrapper represents.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
#[non_exhaustive]
pub enum ComponentKind {
    /// The element node itself.
    Element,
    /// The element's computed/inline style object.
    Style,
    /// The element's `classList`.
    ClassList,
    /// The element's `attributes` collection.
    Attributes,
    /// The element's `dataset` (`data-*` attributes).
    Dataset,
    /// The element's `childNodes` live collection.
    ChildNodes,
}

/// Error returned by DOM API handler invocations.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct DomApiError {
    /// The kind of DOM error (maps to `DOMException` names).
    pub kind: DomApiErrorKind,
    /// A human-readable error message.
    pub message: String,
}

impl DomApiError {
    /// Create a `NotFoundError`.
    pub fn not_found(message: impl Into<String>) -> Self {
        Self {
            kind: DomApiErrorKind::NotFoundError,
            message: message.into(),
        }
    }

    /// Create a `TypeError`.
    pub fn type_error(message: impl Into<String>) -> Self {
        Self {
            kind: DomApiErrorKind::TypeError,
            message: message.into(),
        }
    }

    /// Create a `SyntaxError`.
    pub fn syntax_error(message: impl Into<String>) -> Self {
        Self {
            kind: DomApiErrorKind::SyntaxError,
            message: message.into(),
        }
    }
}

impl fmt::Display for DomApiError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        if self.message.is_empty() {
            write!(f, "{}", self.kind)
        } else {
            write!(f, "{}: {}", self.kind, self.message)
        }
    }
}

impl std::error::Error for DomApiError {}

/// The kind of DOM API error, mapping to standard `DOMException` names.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Hash)]
#[non_exhaustive]
pub enum DomApiErrorKind {
    /// The specified node was not found (`NotFoundError`).
    NotFoundError,
    /// The operation would violate the tree hierarchy (`HierarchyRequestError`).
    HierarchyRequestError,
    /// The object is in an invalid state for the operation (`InvalidStateError`).
    InvalidStateError,
    /// A string argument does not match the expected pattern (`SyntaxError`).
    SyntaxError,
    /// A value is not of the expected type (`TypeError`).
    TypeError,
    /// An unclassified error.
    #[default]
    Other,
}

impl fmt::Display for DomApiErrorKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::NotFoundError => f.write_str("NotFoundError"),
            Self::HierarchyRequestError => f.write_str("HierarchyRequestError"),
            Self::InvalidStateError => f.write_str("InvalidStateError"),
            Self::SyntaxError => f.write_str("SyntaxError"),
            Self::TypeError => f.write_str("TypeError"),
            Self::Other => f.write_str("Error"),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn js_object_ref_roundtrip() {
        let r = JsObjectRef::from_raw(42);
        assert_eq!(r.to_raw(), 42);
        assert_eq!(r, JsObjectRef::from_raw(42));
    }

    #[test]
    fn js_object_ref_display() {
        assert_eq!(JsObjectRef::from_raw(7).to_string(), "JsObjectRef(7)");
    }

    #[test]
    fn component_kind_eq() {
        assert_eq!(ComponentKind::Element, ComponentKind::Element);
        assert_ne!(ComponentKind::Element, ComponentKind::Style);
    }

    #[test]
    fn dom_api_error_display() {
        let err = DomApiError {
            kind: DomApiErrorKind::NotFoundError,
            message: "node not in tree".into(),
        };
        let s = err.to_string();
        assert!(s.contains("NotFoundError"));
        assert!(s.contains("node not in tree"));
        let _: &dyn std::error::Error = &err;
    }

    #[test]
    fn dom_api_error_kind_default() {
        assert_eq!(DomApiErrorKind::default(), DomApiErrorKind::Other);
    }
}
