//! Character-reference tokenizer states (WHATWG HTML §13.2.5.72–80) and
//! the named-entity table (§13.5 "Named character references").
//!
//! The entity table is generated at build time by `build.rs` from the
//! vendored `assets/entities.json` (WHATWG spec snapshot) into a
//! `phf::Map`. The named-reference state does a longest-match probe over
//! that exact-key map (§13.2.5.73, descending-length prefix probe — see
//! the A2 plan decision D-b).

use super::states::{State, Tokenizer};
use crate::StrictParseError;

/// Build-time generated named-entity table.
///
/// Defines `NAMED_ENTITIES: phf::Map<&'static str, &'static str>` (key is
/// the full identifier including the leading `&`, value is the replacement
/// characters) and `MAX_ENTITY_NAME_LEN: usize` (longest key in chars).
mod entities {
    // Generated by build.rs from assets/entities.json; the phf hash seeds
    // are large literals without digit separators.
    #![allow(clippy::unreadable_literal)]
    include!(concat!(env!("OUT_DIR"), "/entities.rs"));
}

impl Tokenizer {
    /// §13.2.5.72 Character reference state.
    pub(super) fn character_reference_state(&mut self) -> Result<(), StrictParseError> {
        self.clear_temp_buffer();
        self.push_temp_buffer('&');
        match self.consume() {
            Some(c) if c.is_ascii_alphanumeric() => {
                self.reconsume_in(State::NamedCharacterReference);
            }
            Some('#') => {
                self.push_temp_buffer('#');
                self.switch_to(State::NumericCharacterReference);
            }
            _ => {
                self.flush_code_points_as_char_ref();
                self.reconsume_in_return_state();
            }
        }
        Ok(())
    }

    /// §13.2.5.73 Named character reference state.
    ///
    /// "Consume the maximum number of characters possible, where the
    /// consumed characters are one of the identifiers in the first column
    /// of the named character references table." Implemented as a
    /// descending-length probe over the exact-key `phf::Map` (D-b).
    pub(super) fn named_character_reference_state(&mut self) -> Result<(), StrictParseError> {
        let start = self.pos();
        let remaining = self.input_len().saturating_sub(start);
        // Candidate total length includes the leading '&' already in the
        // temp buffer, so the most chars we can take after '&' is
        // MAX_ENTITY_NAME_LEN - 1.
        let max_total = entities::MAX_ENTITY_NAME_LEN.min(1 + remaining);

        let mut matched: Option<(usize, &'static str, bool)> = None;
        let mut total = max_total;
        while total >= 2 {
            let k = total - 1; // chars consumed after '&'
            let mut cand = String::with_capacity(total);
            cand.push('&');
            for j in 0..k {
                cand.push(self.input_at(start + j));
            }
            if let Some(&value) = entities::NAMED_ENTITIES.get(cand.as_str()) {
                let ends_semicolon = cand.ends_with(';');
                matched = Some((k, value, ends_semicolon));
                break;
            }
            total -= 1;
        }

        let Some((k, value, ends_semicolon)) = matched else {
            // No identifier matched (§13.2.5.73 → ambiguous ampersand).
            self.flush_code_points_as_char_ref();
            self.switch_to(State::AmbiguousAmpersand);
            return Ok(());
        };

        for j in 0..k {
            let c = self.input_at(start + j);
            self.push_temp_buffer(c);
        }
        self.advance(k);

        // §13.2.5.73 historical attribute case: `&amp` (no semicolon)
        // followed by `=` or an alphanumeric inside an attribute value is
        // flushed literally, not decoded.
        if self.in_attribute_return_state() && !ends_semicolon {
            let next = self.peek_at(self.pos());
            let historical = next == Some('=') || next.is_some_and(|c| c.is_ascii_alphanumeric());
            if historical {
                self.flush_code_points_as_char_ref();
                self.switch_to_return_state();
                return Ok(());
            }
        }

        if !ends_semicolon {
            return Err(self.parse_error("missing-semicolon-after-character-reference"));
        }

        // Replace the temp buffer with the resolved characters.
        self.clear_temp_buffer();
        self.push_temp_buffer_str(value);
        self.flush_code_points_as_char_ref();
        self.switch_to_return_state();
        Ok(())
    }

    /// §13.2.5.74 Ambiguous ampersand state.
    pub(super) fn ambiguous_ampersand_state(&mut self) -> Result<(), StrictParseError> {
        match self.consume() {
            Some(c) if c.is_ascii_alphanumeric() => {
                if self.in_attribute_return_state() {
                    self.push_attr_value(c);
                } else {
                    self.emit_char(c);
                }
            }
            Some(';') => return Err(self.parse_error("unknown-named-character-reference")),
            _ => self.reconsume_in_return_state(),
        }
        Ok(())
    }

    /// §13.2.5.75 Numeric character reference state.
    pub(super) fn numeric_character_reference_state(&mut self) -> Result<(), StrictParseError> {
        self.set_char_ref_code(0);
        match self.consume() {
            Some(c @ ('x' | 'X')) => {
                self.push_temp_buffer(c);
                self.switch_to(State::HexadecimalCharacterReferenceStart);
            }
            _ => self.reconsume_in(State::DecimalCharacterReferenceStart),
        }
        Ok(())
    }

    /// §13.2.5.76 Hexadecimal character reference start state.
    pub(super) fn hexadecimal_character_reference_start_state(
        &mut self,
    ) -> Result<(), StrictParseError> {
        match self.consume() {
            Some(c) if c.is_ascii_hexdigit() => {
                self.reconsume_in(State::HexadecimalCharacterReference);
            }
            _ => return Err(self.parse_error("absence-of-digits-in-numeric-character-reference")),
        }
        Ok(())
    }

    /// §13.2.5.77 Decimal character reference start state.
    pub(super) fn decimal_character_reference_start_state(
        &mut self,
    ) -> Result<(), StrictParseError> {
        match self.consume() {
            Some(c) if c.is_ascii_digit() => self.reconsume_in(State::DecimalCharacterReference),
            _ => return Err(self.parse_error("absence-of-digits-in-numeric-character-reference")),
        }
        Ok(())
    }

    /// §13.2.5.78 Hexadecimal character reference state.
    pub(super) fn hexadecimal_character_reference_state(&mut self) -> Result<(), StrictParseError> {
        match self.consume() {
            Some(c) if c.is_ascii_digit() => {
                self.accumulate_char_ref_code(16, c as u32 - '0' as u32);
            }
            Some(c) if c.is_ascii_uppercase() && c.is_ascii_hexdigit() => {
                self.accumulate_char_ref_code(16, c as u32 - 'A' as u32 + 10);
            }
            Some(c) if c.is_ascii_lowercase() && c.is_ascii_hexdigit() => {
                self.accumulate_char_ref_code(16, c as u32 - 'a' as u32 + 10);
            }
            Some(';') => self.switch_to(State::NumericCharacterReferenceEnd),
            _ => return Err(self.parse_error("missing-semicolon-after-character-reference")),
        }
        Ok(())
    }

    /// §13.2.5.79 Decimal character reference state.
    pub(super) fn decimal_character_reference_state(&mut self) -> Result<(), StrictParseError> {
        match self.consume() {
            Some(c) if c.is_ascii_digit() => {
                self.accumulate_char_ref_code(10, c as u32 - '0' as u32);
            }
            Some(';') => self.switch_to(State::NumericCharacterReferenceEnd),
            _ => return Err(self.parse_error("missing-semicolon-after-character-reference")),
        }
        Ok(())
    }

    /// §13.2.5.80 Numeric character reference end state.
    ///
    /// Validates the accumulated code point. Every spec parse-error branch
    /// (null / out-of-range / surrogate / noncharacter / control) is a
    /// strict reject; only a valid scalar value is decoded and flushed.
    pub(super) fn numeric_character_reference_end_state(&mut self) -> Result<(), StrictParseError> {
        let code = self.char_ref_code();
        if code == 0x00 {
            return Err(self.parse_error("null-character-reference"));
        }
        if code > 0x10_FFFF {
            return Err(self.parse_error("character-reference-outside-unicode-range"));
        }
        if (0xD800..=0xDFFF).contains(&code) {
            return Err(self.parse_error("surrogate-character-reference"));
        }
        if is_noncharacter(code) {
            return Err(self.parse_error("noncharacter-character-reference"));
        }
        if is_control_reference(code) {
            return Err(self.parse_error("control-character-reference"));
        }
        let ch = char::from_u32(code).expect("validated scalar value");
        self.clear_temp_buffer();
        self.push_temp_buffer(ch);
        self.flush_code_points_as_char_ref();
        self.switch_to_return_state();
        Ok(())
    }
}

/// WHATWG noncharacter test (§13.2.5.80): the U+FDD0–U+FDEF block and the
/// last two code points of every plane.
fn is_noncharacter(code: u32) -> bool {
    (0xFDD0..=0xFDEF).contains(&code) || (code & 0xFFFE) == 0xFFFE
}

/// A code point that triggers the §13.2.5.80 control-character-reference
/// parse error: U+000D plus any C0/C1 control that is not ASCII
/// whitespace (tab / LF / FF / space).
fn is_control_reference(code: u32) -> bool {
    let is_control = code <= 0x1F || (0x7F..=0x9F).contains(&code);
    let is_exempt_whitespace = matches!(code, 0x09 | 0x0A | 0x0C | 0x20);
    is_control && !is_exempt_whitespace
}
