//! Tests for the bytecode VM: interpreter, string pool, object heap, and globals.

mod helpers;

mod tests_abort;
mod tests_abort_signal_option;
mod tests_abort_statics;
mod tests_add_event_listener;
mod tests_array_buffer;
mod tests_array_prototype;
mod tests_array_prototype_ext;
mod tests_associated_document;
mod tests_async;
mod tests_async_fetch;
mod tests_bigint;
mod tests_blob;
mod tests_body_mixin;
mod tests_character_data;
mod tests_child_node_mixin;
mod tests_class_list;
mod tests_clone_node;
mod tests_coerce;
mod tests_console;
mod tests_cookie_referrer;
mod tests_core_eval;
mod tests_create_event_object;
mod tests_css_style_declaration;
mod tests_cssom_sheet;
mod tests_data_view;
mod tests_dataset;
mod tests_dispatch_event;
mod tests_document_global;
mod tests_document_members;
mod tests_document_methods;
mod tests_document_type;
mod tests_dom_collection;
mod tests_dom_exception;
mod tests_dom_handler_dispatch;
mod tests_element_attributes;
mod tests_element_methods;
mod tests_element_mutation;
mod tests_element_subtree_collection;
mod tests_element_subtree_query;
mod tests_element_wrapper;
mod tests_event_constructor;
mod tests_event_extras_constructor;
mod tests_event_object;
mod tests_event_target;
mod tests_fetch;
mod tests_forbidden_headers;
mod tests_form_data;
mod tests_function_prototype;
mod tests_gc_audit;
mod tests_generator;
mod tests_headers;
mod tests_history;
mod tests_host_object;
mod tests_html_button_proto;
mod tests_html_element_proto;
mod tests_html_fieldset_proto;
mod tests_html_form_minor_protos;
mod tests_html_form_proto;
mod tests_html_iframe;
mod tests_html_input_proto;
mod tests_html_option_proto;
mod tests_html_select_proto;
mod tests_html_t2a_protos;
mod tests_html_t2b_protos;
mod tests_html_textarea_proto;
mod tests_insert_adjacent;
mod tests_integration_fetch;
mod tests_integration_pr5b;
mod tests_json;
mod tests_location;
mod tests_m4_10_2;
mod tests_m4_11;
mod tests_math;
mod tests_mutation_observer;
mod tests_named_node_map;
mod tests_navigator;
mod tests_node_common;
mod tests_normalize;
mod tests_number;
mod tests_object_complement;
mod tests_parent_node_mixin;
mod tests_performance;
mod tests_post_message;
mod tests_promise;
mod tests_promise_rejection_event;
mod tests_readable_stream;
mod tests_remove_event_listener;
mod tests_request_response;
mod tests_sparse_array;
mod tests_storage;
mod tests_string;
mod tests_string_complement;
mod tests_structured_clone;
mod tests_symbol_iter;
mod tests_text_encoding;
mod tests_timer;
mod tests_to_primitive_fallback;
mod tests_try_catch_finally;
mod tests_typed_array;
mod tests_typed_array_extras;
mod tests_typed_array_hof;
mod tests_typed_array_methods;
mod tests_typed_array_reduce_sort;
mod tests_typed_array_static;
mod tests_ui_event_constructor;
mod tests_url;
mod tests_url_search_params;
mod tests_validity_state;
mod tests_value_types;
mod tests_window_global;
mod tests_window_iframe_props;

// Re-export helpers (eval, eval_bool, drain_fetch_replies, etc.)
// so the sibling `tests_*.rs` files can keep referring to them as
// `super::eval` / `super::eval_bool` / `super::drain_fetch_replies`
// without rewriting their `use super::*;` imports.
pub(crate) use helpers::*;
// `tests_timer.rs` references `super::Vm` directly; preserve that
// path through a single-name re-export.
pub(crate) use super::Vm;
