//! Node cloning methods for [`EcsDom`] (WHATWG DOM §4.4 "Interface
//! Node", "clone a node" / "clone a single node").
//!
//! Split from [`super::tree`] to keep both files below the 1000-line
//! convention (cleanup tranche 2).  The cloning surface is a
//! self-contained subgroup of `EcsDom` methods:
//!
//! - [`EcsDom::clone_attributes`] — single-entity attribute copy
//! - [`EcsDom::clone_character_data`] — single-entity Text / Comment payload copy
//! - [`EcsDom::clone_subtree`] — recursive deep clone (`cloneNode(true)`)
//! - [`EcsDom::clone_node_shallow`] — shallow clone (`cloneNode(false)`)
//!
//! # Per-component clone policy
//!
//! The copy-set below is a *deliberate enumeration*, not an accident
//! of history: every component attachable to a DOM-node entity has an
//! assigned clone policy so a newly added component cannot silently
//! drift out of cloning (the failure mode that once lost `Namespace`).
//!
//! | Policy | Components | Rationale |
//! |---|---|---|
//! | payload copy | `TagType`, `TextContent`, `CommentData`, `DocTypeData`, `Attributes` | per-`NodeKind` payload |
//! | intrinsic copy | `Namespace` | "clone a single node" step 2.4 passes the source namespace to *create an element*; sparse-by-absence, so only foreign elements carry it |
//! | derived copy (src-parity) | `InlineStyle`, `IframeData` | derived from `(tag, ns, attrs)` at creation and copied *together with* `Attributes` so the pair stays consistent; CSSOM read handlers treat an absent `InlineStyle` as an empty declaration block, so the copy is load-bearing for `.style.*` reads on clones |
//! | identity-propagate + state-reset | `CustomElementState` (elidex-custom-elements) | the *is value* slot must propagate but the state always resets to `Undefined`; the type is not nameable from this crate (inverse cargo edge), so the engine-indep clone algorithm in `elidex-dom-api::node_methods::clone` performs it over the src↔dst pairs this module exposes |
//! | cloning-steps hook (deferred) | `FormControlState` (elidex-form) | DOM §4.4 "cloning steps" extension hook (input: value / dirty value flag / checkedness / dirty checkedness flag; textarea: raw value / dirty value flag) — future `MutationEvent::Clone` consumer seam, slot `#11-clone-cloning-steps-event` |
//! | deliberate non-copy | `EventListeners` (elidex-script-session ECS component), `ElementState`, `ScrollState`, `IsModalDialog`, `DialogReturnValue`, `OutputDefaultValue`, `OutputValueOverride`, `ImageData`, `LinkStylesheet`, `InlineFlow`, `InlineFragment`, `InlineFlowLine`, `ColumnFlowSlice`, `ListItemMarker`, `PseudoElementMarker`, `AnonymousTableMarker`, `BackgroundImages`, `AttrEntityCache`, `SlotAssignment`, `SlottedMarker`, `BaseFrozenUrl`, `TemplateContent` (reserved), `Canvas2dContext` / `CanvasDirty` (elidex-web-canvas) | no *clone a node* step copies these (DOM §4.4 — the only explicitly gated copy is the clonable shadow root, step 6); interaction / loader / layout-derived state is regenerated by its owning system, identity caches must never alias |
//! | out-of-domain | `AttrData`, `DocumentBaseUrl` | `Attribute` nodes are rejected by the clone entry point; `DocumentBaseUrl` is Document-entity state owned by `BaseUrlMaintainer` |
//! | structural | `TreeRelation` (fresh), `NodeKind` (copy), `AssociatedDocument` (threaded via `propagate_doc`), `ShadowRoot` / `ShadowHost` (never copied — the dom-api shadow-honor pass replicates clonable shadow roots per spec step 6) | existing semantics |
//!
//! All clone helpers share the WHATWG §4.4 invariants: the returned
//! root is a fresh orphan (no parent / sibling links into the
//! source), `ShadowRoot` / `ShadowHost` components are not copied,
//! and `EventListeners` — an ECS component owned by
//! `elidex-script-session` — is not copied either: no *clone a node*
//! step copies the listener list (the algorithm only gates shadow
//! replication explicitly, step 6).

use crate::components::{
    Attributes, CommentData, DocTypeData, IframeData, InlineStyle, Namespace, NodeKind, TagType,
    TextContent, TreeRelation,
};
use hecs::Entity;

use super::EcsDom;

impl EcsDom {
    // ---- Node cloning (WHATWG DOM §4.4) ----

    /// Copy every attribute from `src` to `dst`, creating an
    /// [`Attributes`] component on `dst` if one does not exist.
    /// No-op if `src` has no attributes or if either entity has been
    /// destroyed.
    pub fn clone_attributes(&mut self, src: Entity, dst: Entity) {
        if !self.all_exist(&[src, dst]) {
            return;
        }
        let snapshot: Option<Attributes> = self
            .world
            .get::<&Attributes>(src)
            .ok()
            .map(|attrs| (*attrs).clone());
        let Some(attrs) = snapshot else { return };
        if self.world.get::<&Attributes>(dst).is_ok() {
            if let Ok(mut existing) = self.world.get::<&mut Attributes>(dst) {
                *existing = attrs;
            }
        } else {
            let _ = self.world.insert_one(dst, attrs);
        }
    }

    /// Copy character data from `src` to `dst`.  Only acts when both
    /// entities share the same character-data [`NodeKind`] —
    /// `Text` → `Text` copies [`TextContent`], `Comment` → `Comment`
    /// copies [`CommentData`].  Mismatched kinds (and non-character-data
    /// entities) are no-ops so the destination never ends up with
    /// both a `TextContent` and a `CommentData` component.
    ///
    /// Currently unused by [`Self::clone_subtree`] — which handles
    /// character data internally when allocating the cloned root —
    /// but kept as a public helper for ad-hoc cross-entity payload
    /// copies.
    pub fn clone_character_data(&mut self, src: Entity, dst: Entity) {
        if !self.all_exist(&[src, dst]) {
            return;
        }
        let src_kind = self.node_kind(src);
        let dst_kind = self.node_kind(dst);
        match (src_kind, dst_kind) {
            (Some(NodeKind::Text), Some(NodeKind::Text)) => {
                let Some(text) = self
                    .world
                    .get::<&TextContent>(src)
                    .ok()
                    .map(|t| t.0.clone())
                else {
                    return;
                };
                if self.world.get::<&TextContent>(dst).is_ok() {
                    if let Ok(mut existing) = self.world.get::<&mut TextContent>(dst) {
                        existing.0 = text;
                    }
                } else {
                    let _ = self.world.insert_one(dst, TextContent(text));
                }
            }
            (Some(NodeKind::Comment), Some(NodeKind::Comment)) => {
                let Some(data) = self
                    .world
                    .get::<&CommentData>(src)
                    .ok()
                    .map(|c| c.0.clone())
                else {
                    return;
                };
                if self.world.get::<&CommentData>(dst).is_ok() {
                    if let Ok(mut existing) = self.world.get::<&mut CommentData>(dst) {
                        existing.0 = data;
                    }
                } else {
                    let _ = self.world.insert_one(dst, CommentData(data));
                }
            }
            _ => {}
        }
    }

    /// Recursively clone `src` and its descendants, returning the
    /// new root entity (WHATWG DOM §4.4 "clone a node").
    ///
    /// Every `(source, clone)` entity pair — the root included — is
    /// pushed onto `pairs` (root first, then descendants in traversal
    /// order).  Callers use the
    /// mapping for per-pair post-passes that this crate cannot
    /// perform itself: `CustomElementState` identity propagation and
    /// per-descendant clonable-shadow-root replication (both live in
    /// `elidex-dom-api::node_methods::clone`, see the module-level
    /// clone-policy table).
    ///
    /// Invariants:
    /// - The returned root has default tree links
    ///   (`parent: None`, `prev_sibling: None`, `next_sibling: None`)
    ///   — i.e. the clone is a fresh orphan.
    /// - Descendant tree links mirror the source structure between
    ///   the newly-allocated entities (parent and sibling pointers
    ///   point inside the clone, never into the source subtree).
    /// - `ShadowRoot` / `ShadowHost` components are **not** copied —
    ///   shadow replication is the dom-api shadow-honor pass's job
    ///   (DOM §4.4 clone-a-node step 6).
    /// - `EventListeners` (an ECS component owned by
    ///   `elidex-script-session`) is **not** copied — no clone-a-node
    ///   step copies the listener list.
    ///
    /// Returns `None` when `src` does not exist, so a missing source
    /// can never alias the original via the returned handle.  `pairs`
    /// is untouched in that case.
    ///
    /// # WHATWG DOM §4.4 "clone a node" — AssociatedDocument propagation
    ///
    /// Per the spec the `document` threaded through the recursion is
    /// the clone's *node document* and differs between branches:
    ///
    /// - **`src` is a Document** — allocate the copy, then replace
    ///   `document` with `copy` (a Document's node document is itself).
    ///   Descendants therefore report the *clone* as their
    ///   `ownerDocument`, not the source document.
    /// - **`src` is not a Document** — keep `document` at the caller's
    ///   initial value (the src node's own `ownerDocument`), so the
    ///   copy and its descendants inherit the src subtree's associated
    ///   document.
    ///
    /// Orphan nodes whose `ownerDocument` is `None` intentionally
    /// produce a clone with no [`crate::AssociatedDocument`] component —
    /// callers relying on the tree-root fallback behaviour remain
    /// unchanged.
    ///
    /// `doc_override` substitutes the threaded document for non-Document
    /// sources (spec: *clone a node* takes `document` as an argument);
    /// `None` derives it from `src`'s own node document.
    #[must_use = "returns None when src does not exist"]
    pub fn clone_subtree(
        &mut self,
        src: Entity,
        pairs: &mut Vec<(Entity, Entity)>,
        doc_override: Option<Entity>,
    ) -> Option<Entity> {
        if !self.contains(src) {
            return None;
        }
        let src_kind = self.node_kind(src);
        // Pick the "document" that gets threaded through the spec's
        // recursion.  For Document clones we defer until after the
        // root has been allocated (it becomes self-referential); for
        // everything else `doc_override` wins when supplied — the
        // shadow-replication pass threads the *operation's* document
        // into shadow subtrees this way (a source-derived document
        // would stamp the original onto a cloned Document's shadow
        // contents) — else we read the src node document up front.
        let document_for_children: Option<Entity> = if matches!(src_kind, Some(NodeKind::Document))
        {
            None
        } else {
            doc_override.or_else(|| self.owner_document(src))
        };
        // Shallow-clone the root.  The root's own AssociatedDocument is
        // set below so we can handle the Document self-ref and the
        // non-Document propagation uniformly.
        let root = self.clone_node_shallow_unchecked(src);
        pairs.push((src, root));
        let root_document = if matches!(src_kind, Some(NodeKind::Document)) {
            root
        } else if let Some(doc) = document_for_children {
            self.set_associated_document(root, doc);
            doc
        } else {
            // Orphan clone — no AssociatedDocument anywhere in the
            // new subtree.  Skip the descendant propagation.
            self.clone_children_recursive(src, root, None, pairs);
            return Some(root);
        };
        if matches!(src_kind, Some(NodeKind::Document)) {
            self.set_associated_document(root, root_document);
        }
        self.clone_children_recursive(src, root, Some(root_document), pairs);
        Some(root)
    }

    /// Allocate a new entity carrying the same [`NodeKind`] and core
    /// component data as `src` (attributes for Elements, text/comment
    /// data for CharacterData, doctype fields for DocumentType) with
    /// no descendants and no parent/sibling links.
    ///
    /// Returns `None` when `src` does not exist so a missing source
    /// can never alias the original via the returned handle.  Tree
    /// relations on the clone are left at defaults — the caller
    /// threads the clone into place.  Does **not** copy `ShadowRoot`
    /// or `EventListeners` (see the module-level clone-policy table).
    ///
    /// Use this for `Node.cloneNode(false)` — it avoids the O(size)
    /// cost of cloning the full subtree only to destroy descendants
    /// that `cloneNode(false)` never wanted.
    #[must_use = "returns None when src does not exist"]
    pub fn clone_node_shallow(&mut self, src: Entity) -> Option<Entity> {
        if !self.contains(src) {
            return None;
        }
        Some(self.clone_node_shallow_unchecked(src))
    }

    /// Unchecked shallow-clone helper: spawns `dst` carrying `src`'s
    /// payload without validating that `src` exists.  Callers must
    /// verify existence first (the public [`clone_node_shallow`]
    /// does exactly that).
    ///
    /// [`clone_node_shallow`]: Self::clone_node_shallow
    fn clone_node_shallow_unchecked(&mut self, src: Entity) -> Entity {
        // Snapshot the payload under a read borrow, then spawn under
        // a mutable borrow.  Spawning a bare tuple first and then
        // inserting components one at a time keeps the hecs API
        // happy (each component needs its own `insert_one` call).
        // `.map(|t| (*t).clone())` — `*` dereferences the hecs `Ref`
        // so `clone()` clones the *data* rather than the reference
        // handle (which would keep `self.world` borrowed and block
        // the subsequent `spawn`).
        let tag = self.world.get::<&TagType>(src).ok().map(|t| (*t).clone());
        let text = self
            .world
            .get::<&TextContent>(src)
            .ok()
            .map(|t| (*t).clone());
        let comment = self
            .world
            .get::<&CommentData>(src)
            .ok()
            .map(|c| (*c).clone());
        let doc_type = self
            .world
            .get::<&DocTypeData>(src)
            .ok()
            .map(|d| (*d).clone());
        let attrs = self
            .world
            .get::<&Attributes>(src)
            .ok()
            .map(|a| (*a).clone());
        // Intrinsic copy (`Namespace` — "clone a single node" step 2.4
        // passes the source namespace; sparse-by-absence, so only
        // foreign elements carry it) and derived copy (`InlineStyle` /
        // `IframeData` — creation-derived pure data copied together
        // with `Attributes` so the pair stays consistent).  All three
        // are element-only components, so one gate on the TagType
        // probe above lets Text/Comment/DocType nodes (the bulk of a
        // typical subtree) skip the archetype lookups entirely.
        let (namespace, inline_style, iframe_data) = if tag.is_some() {
            (
                self.world.get::<&Namespace>(src).ok().map(|n| *n),
                self.world
                    .get::<&InlineStyle>(src)
                    .ok()
                    .map(|s| (*s).clone()),
                self.world
                    .get::<&IframeData>(src)
                    .ok()
                    .map(|i| (*i).clone()),
            )
        } else {
            (None, None, None)
        };
        // Determine the destination `NodeKind`: prefer the source
        // component if present, otherwise infer from the payload
        // (defensive for entities that predate the `NodeKind`
        // component — e.g. anywhere `is_element` would fall back to
        // `TagType`).  Falling back to `Element` unconditionally
        // misclassifies Text/Comment entities that lack `NodeKind`
        // but carry a `TextContent` / `CommentData` payload.
        let kind = self.node_kind(src).unwrap_or_else(|| {
            if tag.is_some() {
                NodeKind::Element
            } else if text.is_some() {
                NodeKind::Text
            } else if comment.is_some() {
                NodeKind::Comment
            } else if doc_type.is_some() {
                NodeKind::DocumentType
            } else {
                NodeKind::Element
            }
        });

        let dst = self.world.spawn((TreeRelation::default(), kind));
        if let Some(tag) = tag {
            let _ = self.world.insert_one(dst, tag);
        }
        if let Some(text) = text {
            let _ = self.world.insert_one(dst, text);
        }
        if let Some(comment) = comment {
            let _ = self.world.insert_one(dst, comment);
        }
        if let Some(doc_type) = doc_type {
            let _ = self.world.insert_one(dst, doc_type);
        }
        if let Some(attrs) = attrs {
            let _ = self.world.insert_one(dst, attrs);
        }
        if let Some(namespace) = namespace {
            let _ = self.world.insert_one(dst, namespace);
        }
        if let Some(inline_style) = inline_style {
            let _ = self.world.insert_one(dst, inline_style);
        }
        if let Some(iframe_data) = iframe_data {
            let _ = self.world.insert_one(dst, iframe_data);
        }
        dst
    }

    /// Clone each child of `src` under `dst`, then every descendant
    /// depth-first.  Uses an explicit `(src_parent, dst_parent)` stack
    /// rather than Rust recursion so trees up to `MAX_ANCESTOR_DEPTH`
    /// (10 000) deep can be cloned without risk of a thread-stack
    /// overflow.  [`ShadowRoot`] children are skipped (matches
    /// `children_iter` semantics — the shadow root is not part of
    /// the light tree).  Every cloned `(src, dst)` pair is appended
    /// to `pairs` for the caller's post-passes.
    fn clone_children_recursive(
        &mut self,
        src: Entity,
        dst: Entity,
        propagate_doc: Option<Entity>,
        pairs: &mut Vec<(Entity, Entity)>,
    ) {
        let mut stack: Vec<(Entity, Entity)> = vec![(src, dst)];
        while let Some((src_parent, dst_parent)) = stack.pop() {
            // Snapshot children before spawning new entities — tree
            // mutations during clone would invalidate
            // `children_iter`'s `next_sibling` reads.
            let kids: Vec<Entity> = self.children(src_parent);
            // Clone each child into the destination, recording the
            // `(src, dst)` pair once in `pairs` — the slice appended
            // this iteration doubles as the stack feed (reversed so
            // the explicit-stack traversal preserves the same
            // left-to-right depth-first ordering the recursive
            // version produced).
            let start = pairs.len();
            for child_src in kids {
                // `kids` was snapshotted from the live tree, so each
                // entry is guaranteed to exist; the unchecked variant
                // skips the redundant `contains` lookup.
                let child_dst = self.clone_node_shallow_unchecked(child_src);
                if let Some(doc) = propagate_doc {
                    self.set_associated_document(child_dst, doc);
                }
                let _ = self.append_child(dst_parent, child_dst);
                pairs.push((child_src, child_dst));
            }
            stack.extend(pairs[start..].iter().rev().copied());
        }
    }
}
