#!/usr/bin/env python3
"""THE GOLDEN MANIFEST of the self-test: one committed, machine-generated line
per mutation row, per control and per case, compared against the live
collection on every run.

WHY A MANIFEST AND NOT DETECTORS (user-approved, 2026-09-23).  Six passes
closed the ways a row, a case or a control could leave the run in silence by
recognising SPELLINGS -- a merge built with `dict(`, a duplicated literal key,
a list bound to the wrong name, a module nobody merges -- and every attestation
found a spelling the detectors did not know (`reg |= fragment`, `{**a, **b}`, a
mid-file `CASES = list(CASES)`, `MUTANTS += [` edited to `MUTANTS = [`).  The
class is open-ended by construction.  So it is closed by COMPARISON: whatever
the spelling, the change shows up as a difference between the collection the
runner is about to execute and the manifest committed beside it.

ONE SOURCE.  `snapshot()` is the one collection call: the runner
(`plan_memo_umbrella_selftest.run`) executes exactly the value it returns, the
check compares exactly that value, and `write()` generates the manifest from
exactly that call.  There is no second enumeration.

DEEP-IMMUTABLE.  The rows the snapshot holds are tuples all the way down, and
the collection step (`plan_memo_selftest_registry.collect`) replaces every
registry module's list with its frozen copy -- so a control that `.pop()`s a
row, or a row's control list, raises instead of changing what runs.

THE WORKFLOW RULE: adding, removing or changing a row, a control or a case
requires regenerating the manifest (`REGENERATE`) and committing its diff; the
diff is the review surface.

THE FILE IS READ FROM THE WORKING TREE, never from the patched-SOURCES map:
`read()` opens `PATH` directly, `PATH` is not a `.py` file so it is outside the
harness's population (`plan_memo_selftest_harness.GLOB`) and no mutation row
can name it -- a row's target must be a module the harness loads or patches.
"""

import collections
import hashlib
import importlib
import pathlib
import types

PATH = pathlib.Path(__file__).resolve().parent / "plan_memo_selftest_manifest.txt"
REGENERATE = "python3 .claude/tools/plan-memo-umbrella-check.py --write-manifest"
HEADER = ("# GENERATED by `%s` -- do not edit by hand.\n"
          "# One line per mutation row, control and case of the self-test; `--self-test`\n"
          "# fails on ANY difference.  Adding, removing or changing a row, control or case\n"
          "# requires regenerating this file and committing its diff.\n" % REGENERATE)

Snapshot = collections.namedtuple("Snapshot", "table rows cases")


def snapshot():
    """THE collection: the control table, the mutation rows and the case
    records, as the runner will execute them."""
    table = importlib.import_module("plan_memo_selftest_controls").registry()
    rows = importlib.import_module("plan_memo_selftest_mutants").mutants()
    cases = importlib.import_module("plan_memo_selftest_cases").cases()
    return Snapshot(types.MappingProxyType(table), rows, cases)


def _esc(text):
    return str(text).replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n")


def _case_digest(c):
    return hashlib.sha256(repr(tuple(c)).encode("utf-8")).hexdigest()[:16]


def lines(snap):
    """The manifest lines of a snapshot, sorted; duplicates KEPT (a row
    collected twice is two lines)."""
    case_names = {c.name for c in snap.cases}
    out = []
    for name, (kind, fn) in snap.table.items():
        where = "case" if name in case_names else "%s.%s" % (fn.__module__, fn.__qualname__)
        out.append("CONTROL\t%s\t%s\t%s" % (kind, _esc(name), where))
    for c in snap.cases:
        out.append("CASE\t%s\t%s\t%s" % (c.kind, _esc(c.name), _case_digest(c)))
    for name, file, _find, _replace, controls in snap.rows:
        out.append("MUTANT\t%s\t%s\t%s" % (_esc(name), file, "|".join(_esc(c) for c in sorted(controls))))
    return sorted(out)


def validate(snap):
    """Generation-time checks, each a property of the one value: a row naming
    no control, a label used twice, a control a row names that the table does
    not hold, a case name used twice.  (A control name used twice cannot reach
    here: `plan_memo_selftest_harness.Registry` refuses it while the table is
    built, so `snapshot()` raises.)"""
    bad = []
    labels = collections.Counter(r[0] for r in snap.rows)
    for name, _file, _find, _replace, controls in snap.rows:
        if not controls:
            bad.append("mutation row %r names no control" % name)
        for c in controls:
            if c not in snap.table:
                bad.append("mutation row %r names %r, which is not a control" % (name, c[:80]))
    bad += ["mutation label %r is used %d times" % (n, k) for n, k in sorted(labels.items()) if k > 1]
    names = collections.Counter(c.name for c in snap.cases)
    bad += ["case name %r is used %d times" % (n, k) for n, k in sorted(names.items()) if k > 1]
    return bad


def read(path=None):
    """The committed manifest's lines, from the WORKING TREE."""
    text = (PATH if path is None else path).read_text(encoding="utf-8")
    return sorted(ln for ln in text.split("\n") if ln and not ln.startswith("#"))


def diff(want, got):
    """(removed, added, changed) between two line lists: changed pairs a
    removed and an added line with the same kind and name."""
    w, g = collections.Counter(want), collections.Counter(got)
    removed = sorted((w - g).elements())
    added = sorted((g - w).elements())
    key = lambda ln: tuple(ln.split("\t")[:2]) if ln.startswith("MUTANT") else tuple(ln.split("\t")[:3])
    rk = {key(x): x for x in removed}
    changed = [(rk[key(a)], a) for a in added if key(a) in rk]
    gone = {x for x, _a in changed}
    came = {a for _x, a in changed}
    return ([x for x in removed if x not in gone], [a for a in added if a not in came], changed)


def verify(snap, want=None):
    """The check `--self-test` runs on the value it then executes: the
    single-value validations, and ANY difference from the committed manifest.
    Returns the failure lines (empty = clean)."""
    bad = ["manifest: %s" % p for p in validate(snap)]
    removed, added, changed = diff(read() if want is None else want, lines(snap))
    if removed or added or changed:
        bad.append("manifest: the collection differs from the committed manifest -- %d removed, "
                   "%d added, %d changed.  If the change is intended, run `%s` and commit the "
                   "diff (adding, removing or changing a row, control or case requires it)"
                   % (len(removed), len(added), len(changed), REGENERATE))
        show = lambda ln: ln.replace("\t", " | ")
        bad += ["manifest:   - %s" % show(x) for x in removed[:20]]
        bad += ["manifest:   + %s" % show(x) for x in added[:20]]
        bad += ["manifest:   ~ %s  ->  %s" % (show(x), show(a)) for x, a in changed[:20]]
    return bad


def write(path=None):
    """`--write-manifest`: regenerate from `snapshot()` -- the same call the
    runner makes -- refusing a value that fails `validate`.  Returns (rc,
    messages); the entry point prints them through its escape."""
    snap = snapshot()
    problems = validate(snap)
    if problems:
        return 1, ["manifest NOT written: %s" % p for p in problems]
    body = lines(snap)
    target = PATH if path is None else path
    target.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    return 0, ["manifest written: %d line(s) to %s" % (len(body), target.name)]
