#!/usr/bin/env python3
"""THE GOLDEN MANIFEST of the self-test: one committed, machine-generated line
per mutation row, per control and per case, compared against the live
collection on every run.

WHY A MANIFEST AND NOT DETECTORS (user-approved, 2026-09-23).  Six passes
closed the ways a row, a case or a control could leave the run in silence by
recognising SPELLINGS -- a merge built with `dict(`, a duplicated literal key,
a list bound to the wrong name, a module nobody merges -- and every attestation
found a spelling the detectors did not know (`reg |= fragment`, `{**a, **b}`, a
mid-file `CASES = list(CASES)`, `MUTANTS += [` edited to `MUTANTS = [`).  The
class is open-ended by construction.  So it is closed by COMPARISON: whatever
the spelling, the change shows up as a difference between the collection the
runner is about to execute and the manifest committed beside it.

ONE SOURCE, AND ONE DOOR.  `_snapshot()` is the one collection call (it
enumerates the cases once and hands them to the table).  It is PRIVATE:
`take()` -- which verifies first and raises on any difference -- is the only
way to obtain a table to run and the rows to mutate, so a runner that skips
the comparison has nothing to execute, and `finish()` reports any verified
control the run did not execute.  `write()` generates from the same
`_snapshot()`.  There is no second enumeration and no second accessor.

DEEP-IMMUTABLE.  The rows the snapshot holds are tuples all the way down, and
the collection step (`plan_memo_selftest_registry.collect`) replaces every
registry module's list with its frozen copy -- so a control that `.pop()`s a
row, or a row's control list, raises instead of changing what runs.

THE WORKFLOW RULE -- THIS IS ITS ONE HOME, and every other mention points
here.  Adding, removing or changing a mutation row, a control or a case --
INCLUDING editing a control's body, its docstring or a comment inside it, and
a row's find / replace, all of which are digested -- requires regenerating the
manifest (`REGENERATE`) and committing its diff; the diff is the review
surface.  A comment-only edit to a control is a legitimate reason to
regenerate: the digest is of the source BLOCK, which is the price of a digest
that does not change with the interpreter.

WHAT THE MANIFEST DOES NOT PROMISE, and where the boundary runs.
  * It pins every control's identity, kind, defining function and SOURCE
    digest -- not that a control CAN GO RED.  Controls named by no mutation
    row have nothing proving they would fail if their subject broke; that gap,
    its current size and the command that measures it are in
    `docs/plans/2026-09-plan-memo-selftest-registry.md`, and it is not closed
    here.
  * The digest covers a control's DEFINITION BLOCK.  MODULE-LEVEL DATA a
    control reads -- a fixture table, a planted directory's file map, a
    complement -- is outside it: weakening such a table changes no manifest
    line, and what holds it is the partner arm that reads it (measured: the
    population partner's planted `_DIR` is one, and dropping one of its entries
    leaves the manifest identical).

THE FILE IS READ FROM THE WORKING TREE, never from the patched-SOURCES map:
`read()` opens `PATH` directly, `PATH` is not a `.py` file so it is outside the
harness's population (`plan_memo_selftest_harness.GLOB`) and no mutation row
can name it -- a row's target must be a module the harness loads or patches.
"""

import collections
import hashlib
import importlib
import pathlib
import textwrap
import types

PATH = pathlib.Path(__file__).resolve().parent / "plan_memo_selftest_manifest.txt"
REGENERATE = "python3 .claude/tools/plan-memo-umbrella-check.py --write-manifest"
HEADER = ("# GENERATED by `%s` -- do not edit by hand.\n"
          "# One line per mutation row, control and case of the self-test; `--self-test`\n"
          "# fails on ANY difference.  Adding, removing or changing a row, control or case --\n"
          "# a control's body, docstring or comments included -- requires regenerating this\n"
          "# file and committing its diff (the rule's home is the module docstring of\n"
          "# plan_memo_selftest_manifest.py).\n" % REGENERATE)

Snapshot = collections.namedtuple("Snapshot", "table rows cases")
_TAKEN = {}
"""id(Taken) -> its execution Counter, for the `Taken`s `take()` itself made.
A `Taken` built by anything else is not in here, so `finish()` refuses it: the
accounting is not reachable, let alone writable, from outside."""


Taken = collections.namedtuple("Taken", "entries rows")
"""The verified collection: the entries to run and the rows to mutate.
IMMUTABLE -- a `__slots__` class stood here for one commit and a runner could
then FILTER what it had taken (`taken.entries = ...`) and run a smaller table
at rc 0.  The accounting lives in `_TAKEN`, keyed on identity, so there is no
`seen` to forge either."""


class ManifestError(RuntimeError):
    """Raised by `take()`: the collection differs from the committed manifest,
    fails a generation-time validation, or the manifest cannot be read.  It is
    NOT caught: a run that cannot compare must not run."""


def _wrap(name, fn, seen):
    """`fn`, COUNTING in `seen` that the control ran -- what lets `finish()`
    report a verified control the run did not execute, or ran twice."""
    def run(M):
        seen[name] = seen.get(name, 0) + 1
        return fn(M)
    return run


_SNAP = []
"""THE collection of this process, built once: one collection means ONE, and
three collections per control was 27 % of the mutation run's wall clock."""


def _build():
    """Build the collection: the cases are enumerated ONCE and handed to the
    table (I3), and the rows are collected once."""
    case_rows = importlib.import_module("plan_memo_selftest_cases").cases()
    table = importlib.import_module("plan_memo_selftest_controls").registry(case_rows)
    rows = importlib.import_module("plan_memo_selftest_mutants").mutants()
    return Snapshot(types.MappingProxyType(table), rows, case_rows)


def _snapshot():
    """THE collection -- private, because `take()` is the only way to obtain a
    table to RUN (the manifest attestation's CRIT-1: the runner could execute a
    value it had not compared), and built ONCE per process."""
    if not _SNAP:
        _SNAP.append(_build())
    return _SNAP[0]


def _esc(text):
    """INJECTIVE: every separator this format uses is escaped (16 control names
    hold a `|`, which the row line uses between control names -- the manifest
    attestation's M4)."""
    return (str(text).replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n")
            .replace("|", "\\p"))


def _case_digest(c):
    return hashlib.sha256(repr(tuple(c)).encode("utf-8")).hexdigest()[:16]


_DIGESTS = {}
_FILES = {}


def _module_text(code):
    """The text the module that defines `code` was EXEC'D from: the harness's
    `SOURCES` map when it holds the file (a mutation row's patched text lives
    there), the file on disk otherwise.

    ⚠ Not `inspect.getsource`, which reads the FILE: a module the harness
    exec'd from patched text would then digest the text on disk, and a module
    with no file at all would fall back to a constant -- both of them the
    silent equality this digest exists to prevent."""
    file = pathlib.Path(code.co_filename).name
    harness = importlib.import_module("plan_memo_selftest_harness")
    text = harness.SOURCES.get(file)
    if text is None:
        # the file is read ONCE per path (a module's file does not change
        # under a run; a PATCHED module's text comes from `SOURCES` above)
        text = _FILES.get(code.co_filename)
    if text is None:
        try:
            text = pathlib.Path(code.co_filename).read_text(encoding="utf-8")
            _FILES[code.co_filename] = text
        except OSError as e:
            raise ManifestError(printable(
                "the source of %s (%s:%d) is unreachable (%s), so its digest cannot be taken -- "
                "run `%s` from a checkout where every module has its file"
                % (code.co_name, file, code.co_firstlineno, e, REGENERATE)))
    return text


def _source_digest(code):
    """A digest of the SOURCE TEXT that defines a function -- its `def` or
    `lambda` block, nested definitions, comments and docstring included.

    ⚠ IT WAS THE BYTECODE until the CI attestation, and that made the manifest
    an INTERPRETER-VERSION artefact: `co_code` differs between 3.9, 3.12 and
    3.14, so every control line changed and the always-run wire would have been
    red on the CI runner's python3 while green here.  The source text is the
    thing a reader edits, and it is the same on every interpreter.

    THE TRADE-OFF, stated where the workflow rule is: because comments and
    docstrings are inside the block, a comment-only edit to a control changes
    its line and is a legitimate reason to regenerate the manifest.  The
    alternative -- digesting only what the compiler kept -- is what made the
    digest version-dependent, and left a docstring or a constant outside it.

    THE LIMIT: the block of a `lambda` is its LINE, so two lambdas written on
    one line have one digest.  Every control the table holds is a `def` or a
    lambda on a line of its own."""
    import inspect
    text = _module_text(code)
    key = (code.co_filename, code.co_firstlineno, code.co_name, hash(text))
    if key not in _DIGESTS:
        block = "".join(inspect.getblock(text.splitlines(True)[code.co_firstlineno - 1:]))
        _DIGESTS[key] = hashlib.sha256(
            textwrap.dedent(block).encode("utf-8", "replace")).hexdigest()[:16]
    return _DIGESTS[key]


def _fn_id(fn):
    """The control's identity in the manifest: where it is defined, and a
    digest of its source.  (`__code__` is present on every callable the table
    holds -- measured -- so there is no no-code arm here.)"""
    return "%s.%s#%s" % (getattr(fn, "__module__", "?"), getattr(fn, "__qualname__", "?"),
                         _source_digest(fn.__code__))


def lines(snap):
    """The manifest lines of a snapshot, sorted; duplicates KEPT (a row
    collected twice is two lines -- the partner plants one).  Every control
    line carries the defining function AND a digest of its SOURCE TEXT, so a
    control re-pointed to a stub or re-bodied is a changed line whether it came
    from a case or not;
    every row line carries a digest of its (find, replace), so two rows'
    edits cannot be swapped in silence."""
    out = []
    for name, (kind, fn) in snap.table.items():
        out.append("CONTROL\t%s\t%s\t%s" % (kind, _esc(name), _fn_id(fn)))
    for c in snap.cases:
        out.append("CASE\t%s\t%s\t%s" % (c.kind, _esc(c.name), _case_digest(c)))
    for name, file, find, replace, controls in snap.rows:
        edit = hashlib.sha256(("%s\x00%s" % (find, replace)).encode("utf-8")).hexdigest()[:16]
        out.append("MUTANT\t%s\t%s\t%s\t%s"
                   % (_esc(name), file, edit, "|".join(_esc(c) for c in sorted(controls))))
    return sorted(out)


def validate(snap):
    """Generation-time checks, each a property of the one value: a row naming
    no control, a label used twice, a control a row names that the table does
    not hold, a case name used twice, an EDIT repeated by two rows (the
    manifest attestation's I2, a regression this restores: the row that runs
    second proves nothing its twin did not).  (A control name used twice cannot reach
    here: `plan_memo_selftest_harness.Registry` refuses it while the table is
    built, so `snapshot()` raises.)"""
    bad = []
    labels = collections.Counter(r[0] for r in snap.rows)
    edits = collections.Counter((r[1], r[2], r[3]) for r in snap.rows)
    bad += ["mutation rows repeat one edit in %s %d times" % (f, k)
            for (f, _find, _replace), k in sorted(edits.items()) if k > 1]
    for name, _file, _find, _replace, controls in snap.rows:
        if not controls:
            bad.append("mutation row %r names no control" % name)
        for c in controls:
            if c not in snap.table:
                bad.append("mutation row %r names %r, which is not a control" % (name, c[:80]))
    bad += ["mutation label %r is used %d times" % (n, k) for n, k in sorted(labels.items()) if k > 1]
    names = collections.Counter(c.name for c in snap.cases)
    bad += ["case name %r is used %d times" % (n, k) for n, k in sorted(names.items()) if k > 1]
    return bad


def read(path=None):
    """The committed manifest's lines, from the WORKING TREE.  EVERY fault
    shape -- missing, a directory, unreadable, empty, undecodable -- is one
    `ManifestError` naming the file and the regenerate command (M2), never a
    raw traceback."""
    target = PATH if path is None else path
    try:
        text = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        raise ManifestError(printable(
            "the golden manifest %s cannot be read (%s: %s) -- run `%s` and commit it"
            % (target.name, type(e).__name__, e, REGENERATE)))
    body = sorted(ln for ln in text.split("\n") if ln and not ln.startswith("#"))
    if not body:
        raise ManifestError(printable("the golden manifest %s is empty -- run `%s` and commit it"
                                       % (target.name, REGENERATE)))
    return body


def diff(want, got):
    """(removed, added, changed) between two line lists: changed pairs a
    removed and an added line with the same kind and name."""
    w, g = collections.Counter(want), collections.Counter(got)
    removed = sorted((w - g).elements())
    added = sorted((g - w).elements())
    key = lambda ln: tuple(ln.split("\t")[:2]) if ln.startswith("MUTANT") else tuple(ln.split("\t")[:3])
    rk = {key(x): x for x in removed}
    changed = [(rk[key(a)], a) for a in added if key(a) in rk]
    gone = {x for x, _a in changed}
    came = {a for _x, a in changed}
    return ([x for x in removed if x not in gone], [a for a in added if a not in came], changed)


def take():
    """THE ONLY public way to obtain a table to run and the rows to mutate: it
    verifies THE collection (there is no `want` to hand it, and no public
    accessor for the snapshot) and RAISES `ManifestError` on any difference, so
    a runner that skips the comparison has nothing to execute (CRIT-1).

    Each control is handed back WRAPPED, counting that it ran; `finish()` --
    which returns the counts the summary line prints, so it cannot be dropped
    -- RAISES when the set of controls that RAN is not exactly the verified
    table, each exactly once."""
    snap = _snapshot()
    bad = verify(snap)
    if bad:
        # each line is escaped, the newline is layout (escaping twice is
        # idempotent: an escaped line holds no C0 byte left to escape)
        raise ManifestError("\n".join(printable(line) for line in bad))
    seen = {}
    entries = tuple((name, kind, _wrap(name, fn, seen)) for name, (kind, fn) in snap.table.items())
    taken = Taken(entries, snap.rows)
    _TAKEN[id(taken)] = (taken, seen, snap.rows)
    return taken


def finish(taken):
    """The counts the runner REPORTS -- of what actually ran -- and the audit:
    a verified control that did not run, or ran twice, RAISES; so does a
    `Taken` this module did not make."""
    held = _TAKEN.get(id(taken))
    if held is None or held[0] is not taken:
        raise ManifestError(printable(
            "manifest: this collection was not taken from the manifest -- `take()` is the only "
            "door, and `%s` says what to do when it refuses one" % REGENERATE))
    seen = held[1]
    if taken.rows is not held[2]:
        raise ManifestError(printable(
            "manifest: the rows handed to the mutation proof are not the verified ones -- %d of "
            "%d rows would run" % (len(taken.rows), len(held[2]))))
    verified = [(name, kind) for name, kind, _fn in taken.entries]
    wrong = audit(verified, seen)
    if wrong:
        raise ManifestError(printable(
            "manifest: %d control(s) did not run exactly once, so the run did not execute the "
            "table it compared: %s" % (len(wrong), "; ".join(wrong[:3]))))
    return counts(verified, seen)


def audit(verified, seen):
    """Every control of the verified table that did not run EXACTLY once, and
    every control that ran and is not in it."""
    known = dict(verified)
    return (["%s ran %d time(s)" % (name[:60], seen.get(name, 0)) for name, _k in verified
             if seen.get(name, 0) != 1]
            + ["%s is not in the verified table" % name[:60] for name in sorted(seen)
               if name not in known])


def counts(verified, seen):
    """The per-kind counts the summary line prints -- of what RAN, not of what
    was compared (they are equal only because `audit` is empty)."""
    out = {}
    for name, kind in verified:
        out[kind] = out.get(kind, 0) + seen.get(name, 0)
    return out


_ESCAPE = []


def printable(text):
    """The report boundary's escape, taken from the checker -- this module does
    not spell a second one -- and REMEMBERED, so it does not depend on load
    state.

    ⚠ IT WAS "the loaded checker, or the identity" for one commit, and the
    runner `unload()`s before it reports: a control name carrying a BEL then
    reached stderr RAW through the raised error, which is the class the escape
    exists to close.  The escape is captured the first time the checker is
    loaded (every path that reports loads it first) and used from then on."""
    import sys as _sys
    checker = _sys.modules.get("plan_memo_umbrella_check")
    if checker is not None:
        del _ESCAPE[:]
        _ESCAPE.append(checker.printable)
    return _ESCAPE[0](text) if _ESCAPE else text


def verify(snap, want=None):
    """The check `--self-test` runs on the value it then executes: the
    single-value validations, and ANY difference from the committed manifest.
    Returns the failure lines (empty = clean)."""
    bad = [printable("manifest: %s" % p) for p in validate(snap)]
    removed, added, changed = diff(read() if want is None else want, lines(snap))
    if removed or added or changed:
        bad.append(printable("manifest: the collection differs from the committed manifest -- %d removed, "
                   "%d added, %d changed.  If the change is intended, run `%s` and commit the "
                   "diff (adding, removing or changing a row, control or case -- including "
                   "editing a control's body or a row's find/replace, which are digested -- "
                   "requires it)"
                   % (len(removed), len(added), len(changed), REGENERATE)))
        show = lambda ln: printable(ln.replace("\t", " | "))
        bad += ["manifest:   - %s" % show(x) for x in removed[:20]]
        bad += ["manifest:   + %s" % show(x) for x in added[:20]]
        bad += ["manifest:   ~ %s  ->  %s" % (show(x), show(a)) for x, a in changed[:20]]
    return bad


def write(path=None):
    """`--write-manifest`: regenerate from `snapshot()` -- the same call the
    runner makes -- refusing a value that fails `validate`.  Returns (rc,
    messages); the entry point prints them through its escape."""
    snap = _snapshot()
    problems = validate(snap)
    if problems:
        return 1, ["manifest NOT written: %s" % p for p in problems]
    body = lines(snap)
    target = PATH if path is None else path
    target.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    return 0, ["manifest written: %d line(s) to %s" % (len(body), target.name)]
