#!/usr/bin/env python3
"""THE GOLDEN MANIFEST of the self-test: one committed, machine-generated line
per mutation row, per control and per case, compared against the live
collection on every run.

WHY A MANIFEST AND NOT DETECTORS (user-approved, 2026-09-23).  Six passes
closed the ways a row, a case or a control could leave the run in silence by
recognising SPELLINGS -- a merge built with `dict(`, a duplicated literal key,
a list bound to the wrong name, a module nobody merges -- and every attestation
found a spelling the detectors did not know (`reg |= fragment`, `{**a, **b}`, a
mid-file `CASES = list(CASES)`, `MUTANTS += [` edited to `MUTANTS = [`).  The
class is open-ended by construction.  So it is closed by COMPARISON: whatever
the spelling, the change shows up as a difference between the collection the
runner is about to execute and the manifest committed beside it.

ONE SOURCE, AND ONE DOOR.  `_snapshot()` is the one collection call (it
enumerates the cases once and hands them to the table).  It is PRIVATE:
`take()` -- which verifies first and raises on any difference -- is the only
way to obtain a table to run and the rows to mutate, so a runner that skips
the comparison has nothing to execute, and `finish()` reports any verified
control the run did not execute.  `write()` generates from the same
`_snapshot()`.  There is no second enumeration and no second accessor.

DEEP-IMMUTABLE.  The rows the snapshot holds are tuples all the way down, and
the collection step (`plan_memo_selftest_registry.collect`) replaces every
registry module's list with its frozen copy -- so a control that `.pop()`s a
row, or a row's control list, raises instead of changing what runs.

THE WORKFLOW RULE: adding, removing or changing a row, a control or a case --
including EDITING A CONTROL'S BODY or a row's find/replace, both of which are
digested here -- requires regenerating the manifest (`REGENERATE`) and
committing its diff; the diff is the review surface.

THE FILE IS READ FROM THE WORKING TREE, never from the patched-SOURCES map:
`read()` opens `PATH` directly, `PATH` is not a `.py` file so it is outside the
harness's population (`plan_memo_selftest_harness.GLOB`) and no mutation row
can name it -- a row's target must be a module the harness loads or patches.
"""

import collections
import functools
import hashlib
import importlib
import pathlib
import types

PATH = pathlib.Path(__file__).resolve().parent / "plan_memo_selftest_manifest.txt"
REGENERATE = "python3 .claude/tools/plan-memo-umbrella-check.py --write-manifest"
HEADER = ("# GENERATED by `%s` -- do not edit by hand.\n"
          "# One line per mutation row, control and case of the self-test; `--self-test`\n"
          "# fails on ANY difference.  Adding, removing or changing a row, control or case\n"
          "# requires regenerating this file and committing its diff.\n" % REGENERATE)

Snapshot = collections.namedtuple("Snapshot", "table rows cases")
Taken = collections.namedtuple("Taken", "entries rows seen")


class ManifestError(RuntimeError):
    """Raised by `take()`: the collection differs from the committed manifest,
    fails a generation-time validation, or the manifest cannot be read.  It is
    NOT caught: a run that cannot compare must not run."""


def _wrap(name, fn, seen):
    """`fn`, recording in `seen` that the control ran -- what lets `finish()`
    report a verified control the run did not execute."""
    def run(M):
        seen.add(name)
        return fn(M)
    return run


def _snapshot():
    """THE collection -- private, because `take()` is the only way to obtain a
    table to RUN (the manifest attestation's CRIT-1: the runner could execute a
    value it had not compared).  The cases are enumerated ONCE and handed to
    the table (I3)."""
    case_rows = importlib.import_module("plan_memo_selftest_cases").cases()
    table = importlib.import_module("plan_memo_selftest_controls").registry(case_rows)
    rows = importlib.import_module("plan_memo_selftest_mutants").mutants()
    return Snapshot(types.MappingProxyType(table), rows, case_rows)


def _esc(text):
    """INJECTIVE: every separator this format uses is escaped (16 control names
    hold a `|`, which the row line uses between control names -- the manifest
    attestation's M4)."""
    return (str(text).replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n")
            .replace("|", "\\p"))


@functools.lru_cache(maxsize=None)
def _case_digest(c):
    return hashlib.sha256(repr(tuple(c)).encode("utf-8")).hexdigest()[:16]


@functools.lru_cache(maxsize=None)
def _code_digest(code):
    """A digest of a code object: its bytecode, names and constants, recursing
    into nested code objects (a `repr` of one carries its ADDRESS, which is not
    deterministic).  A control whose BODY is replaced by a stub, or a case
    control re-pointed to a lambda, changes here (M1, I4)."""
    parts = [code.co_name, code.co_code.hex(), repr(code.co_names), repr(code.co_varnames),
             str(len(code.co_consts))]
    # ⚠ The VALUES of the constants are deliberately not digested: a constant
    # set's `repr` order depends on hash randomisation, so a digest over it
    # would differ between two runs of the same source.  Nested code objects
    # ARE digested, so a body hidden one `lambda` deeper still shows.
    for const in code.co_consts:
        if hasattr(const, "co_code"):
            parts.append(_code_digest(const))
    return hashlib.sha256("\x00".join(parts).encode("utf-8", "replace")).hexdigest()[:16]


def _fn_id(fn):
    code = getattr(fn, "__code__", None)
    return "%s.%s#%s" % (getattr(fn, "__module__", "?"), getattr(fn, "__qualname__", "?"),
                         _code_digest(code) if code is not None else "nocode")


def lines(snap):
    """The manifest lines of a snapshot, sorted; duplicates KEPT (a row
    collected twice is two lines -- the partner plants one).  Every control
    line carries the defining function AND a digest of its code, so a control
    re-pointed to a stub is a changed line whether it came from a case or not;
    every row line carries a digest of its (find, replace), so two rows'
    edits cannot be swapped in silence."""
    out = []
    for name, (kind, fn) in snap.table.items():
        out.append("CONTROL\t%s\t%s\t%s" % (kind, _esc(name), _fn_id(fn)))
    for c in snap.cases:
        out.append("CASE\t%s\t%s\t%s" % (c.kind, _esc(c.name), _case_digest(c)))
    for name, file, find, replace, controls in snap.rows:
        edit = hashlib.sha256(("%s\x00%s" % (find, replace)).encode("utf-8")).hexdigest()[:16]
        out.append("MUTANT\t%s\t%s\t%s\t%s"
                   % (_esc(name), file, edit, "|".join(_esc(c) for c in sorted(controls))))
    return sorted(out)


def validate(snap):
    """Generation-time checks, each a property of the one value: a row naming
    no control, a label used twice, a control a row names that the table does
    not hold, a case name used twice, an EDIT repeated by two rows (the
    manifest attestation's I2, a regression this restores: the row that runs
    second proves nothing its twin did not).  (A control name used twice cannot reach
    here: `plan_memo_selftest_harness.Registry` refuses it while the table is
    built, so `snapshot()` raises.)"""
    bad = []
    labels = collections.Counter(r[0] for r in snap.rows)
    edits = collections.Counter((r[1], r[2], r[3]) for r in snap.rows)
    bad += ["mutation rows repeat one edit in %s %d times" % (f, k)
            for (f, _find, _replace), k in sorted(edits.items()) if k > 1]
    for name, _file, _find, _replace, controls in snap.rows:
        if not controls:
            bad.append("mutation row %r names no control" % name)
        for c in controls:
            if c not in snap.table:
                bad.append("mutation row %r names %r, which is not a control" % (name, c[:80]))
    bad += ["mutation label %r is used %d times" % (n, k) for n, k in sorted(labels.items()) if k > 1]
    names = collections.Counter(c.name for c in snap.cases)
    bad += ["case name %r is used %d times" % (n, k) for n, k in sorted(names.items()) if k > 1]
    return bad


def read(path=None):
    """The committed manifest's lines, from the WORKING TREE.  EVERY fault
    shape -- missing, a directory, unreadable, empty, undecodable -- is one
    `ManifestError` naming the file and the regenerate command (M2), never a
    raw traceback."""
    target = PATH if path is None else path
    try:
        text = target.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as e:
        raise ManifestError("the golden manifest %s cannot be read (%s: %s) -- run `%s` and commit "
                            "it" % (target.name, type(e).__name__, e, REGENERATE))
    body = sorted(ln for ln in text.split("\n") if ln and not ln.startswith("#"))
    if not body:
        raise ManifestError("the golden manifest %s is empty -- run `%s` and commit it"
                            % (target.name, REGENERATE))
    return body


def diff(want, got):
    """(removed, added, changed) between two line lists: changed pairs a
    removed and an added line with the same kind and name."""
    w, g = collections.Counter(want), collections.Counter(got)
    removed = sorted((w - g).elements())
    added = sorted((g - w).elements())
    key = lambda ln: tuple(ln.split("\t")[:2]) if ln.startswith("MUTANT") else tuple(ln.split("\t")[:3])
    rk = {key(x): x for x in removed}
    changed = [(rk[key(a)], a) for a in added if key(a) in rk]
    gone = {x for x, _a in changed}
    came = {a for _x, a in changed}
    return ([x for x in removed if x not in gone], [a for a in added if a not in came], changed)


def take(want=None):
    """THE ONLY public way to obtain a table to run and the rows to mutate: it
    verifies first and RAISES `ManifestError` on any difference, so a runner
    that skips the comparison has nothing to execute (CRIT-1).

    Each control is handed back WRAPPED, recording that it ran; `finish()`
    then reports any verified control the runner did not execute -- which is
    what catches a runner that filters the table after comparing it, or runs a
    SECOND collection instead of this one."""
    snap = _snapshot()
    bad = verify(snap, want)
    if bad:
        raise ManifestError("\n".join(bad))
    seen = set()
    entries = tuple((name, kind, _wrap(name, fn, seen)) for name, (kind, fn) in snap.table.items())
    return Taken(entries, snap.rows, seen)


def finish(taken):
    """(counts by kind, failures): the counts the runner reports, and the
    verified controls it did NOT execute -- so the summary line cannot be
    printed without this audit."""
    counts = {}
    for name, kind, _fn in taken.entries:
        counts[kind] = counts.get(kind, 0) + 1
    missing = sorted(name for name, _k, _f in taken.entries if name not in taken.seen)
    fails = ["manifest: %d verified control(s) were never executed -- the run must execute the "
             "table it compared: %s" % (len(missing), "; ".join(m[:60] for m in missing[:3]))] if missing else []
    return counts, fails


def verify(snap, want=None):
    """The check `--self-test` runs on the value it then executes: the
    single-value validations, and ANY difference from the committed manifest.
    Returns the failure lines (empty = clean)."""
    bad = ["manifest: %s" % p for p in validate(snap)]
    removed, added, changed = diff(read() if want is None else want, lines(snap))
    if removed or added or changed:
        bad.append("manifest: the collection differs from the committed manifest -- %d removed, "
                   "%d added, %d changed.  If the change is intended, run `%s` and commit the "
                   "diff (adding, removing or changing a row, control or case -- including "
                   "editing a control's body or a row's find/replace, which are digested -- "
                   "requires it)"
                   % (len(removed), len(added), len(changed), REGENERATE))
        show = lambda ln: ln.replace("\t", " | ")
        bad += ["manifest:   - %s" % show(x) for x in removed[:20]]
        bad += ["manifest:   + %s" % show(x) for x in added[:20]]
        bad += ["manifest:   ~ %s  ->  %s" % (show(x), show(a)) for x, a in changed[:20]]
    return bad


def write(path=None):
    """`--write-manifest`: regenerate from `snapshot()` -- the same call the
    runner makes -- refusing a value that fails `validate`.  Returns (rc,
    messages); the entry point prints them through its escape."""
    snap = _snapshot()
    problems = validate(snap)
    if problems:
        return 1, ["manifest NOT written: %s" % p for p in problems]
    body = lines(snap)
    target = PATH if path is None else path
    target.write_text(HEADER + "\n".join(body) + "\n", encoding="utf-8")
    return 0, ["manifest written: %d line(s) to %s" % (len(body), target.name)]
