//! Pre-interned string IDs and well-known Symbol IDs, built once at
//! `Vm::new` time and consulted on every property operation,
//! identifier comparison, and event-object construction.
//!
//! Split out of `mod.rs` to keep that file under the project's
//! 1000-line convention.  The structs themselves are passive data
//! (fields are `Copy` newtypes) — the only behaviour here is the
//! `new` constructors that pre-intern each name on the crate's
//! `StringPool` / `SymbolRecord` table.
//!
//! ## `WellKnownStrings` shape
//!
//! Field declarations and intern-time literals are unified through
//! the [`define_well_known_strings!`] macro: each `field => "literal"`
//! pair is the **single source of truth** for both the
//! `WellKnownStrings` struct field and its
//! `WellKnownStrings::intern_all` initialiser.  Eliminates the
//! prior 388-pair manual sync surface (a typo in the literal that
//! diverged from the field name was an undetectable runtime bug;
//! now the two sides cannot drift).
//!
//! Sections are grouped by spec area; each `"section name" { … }`
//! block is purely a navigation marker (the macro discards the
//! string at expansion time, so it carries no runtime cost).

use super::pools::StringPool;
use super::value::{StringId, SymbolId, SymbolRecord};

/// Declarative macro that emits both the `WellKnownStrings` struct
/// and its `intern_all` initialiser from a single ordered list of
/// `field => "literal"` pairs.  See module docs for the rationale.
///
/// The `"section name" { ... }` blocks act as navigation markers
/// in the source — the macro consumes the literal but doesn't emit
/// it (so no per-section runtime overhead).  Each field accepts an
/// optional `$(#[$attr:meta])*` attribute prefix which gets emitted
/// on the generated struct field — `///` rustdoc comments work as
/// `#[doc = "..."]` attrs and survive the expansion intact.  Plain
/// `//` line comments inside the macro invocation are stripped at
/// parse time (transparent to the expansion) and serve as inline
/// rationale for human readers.  Pure declarative macro_rules; no
/// proc-macro infrastructure needed.
macro_rules! define_well_known_strings {
    (
        $(
            $_section:literal {
                $(
                    $(#[$attr:meta])*
                    $field:ident => $literal:literal
                ),* $(,)?
            }
        )*
    ) => {
        /// Frequently used interned string IDs, cached at VM creation.
        ///
        /// Generated by [`define_well_known_strings!`] — see module
        /// docs for the rationale.  Field names and intern literals
        /// share a single source of truth in the macro invocation
        /// below, so no `field`/`literal` divergence is possible.
        #[allow(dead_code)] // Fields used by interpreter and future built-ins.
        pub(crate) struct WellKnownStrings {
            $($(
                $(#[$attr])*
                pub(crate) $field: StringId,
            )*)*
        }

        impl WellKnownStrings {
            /// Intern every well-known name on `strings` and return
            /// the populated table.  Must be the only caller to
            /// populate `WellKnownStrings` — the fields carry
            /// expectations (e.g. `empty` is literally `intern("")`)
            /// that other VM code relies on without re-checking.
            pub(crate) fn intern_all(strings: &mut StringPool) -> Self {
                Self {
                    $($( $field: strings.intern($literal), )*)*
                }
            }
        }
    };
}

define_well_known_strings! {
    "core" {
        undefined => "undefined",
        null => "null",
        r#true => "true",
        r#false => "false",
        nan => "NaN",
        infinity => "Infinity",
        neg_infinity => "-Infinity",
        zero => "0",
        empty => "",
        prototype => "prototype",
        constructor => "constructor",
        length => "length",
        name => "name",
        message => "message",
        log => "log",
        error => "error",
        warn => "warn",
        object_type => "object",
        boolean_type => "boolean",
        number_type => "number",
        string_type => "string",
        function_type => "function",
        symbol_type => "symbol",
        bigint_type => "bigint",
        object_to_string => "[object Object]",
        next => "next",
        value => "value",
        done => "done",
        return_str => "return",
        last_index => "lastIndex",
        index => "index",
        input => "input",
        join => "join",
        to_json => "toJSON",
        get => "get",
        set => "set",
        enumerable => "enumerable",
        configurable => "configurable",
        writable => "writable",
        source => "source",
        /// `MessageEvent.ports` — pre-interned so the postMessage
        /// shape extension picks the StringId out of `WellKnownStrings`
        /// instead of round-tripping through `strings.intern("ports")`
        /// per dispatched event.
        ports => "ports",
        flags => "flags",
        status => "status",
        fulfilled => "fulfilled",
        rejected => "rejected",
        reason => "reason",
        errors => "errors",
        aggregate_error => "AggregateError",
    }

    "Event-dispatch identifiers (PR3)" {
        // Property names installed on every event object — pre-interned
        // here to avoid a HashMap lookup per name per dispatch.  Listener
        // option keys (`capture`/`once`/`passive`) live here too since
        // every `addEventListener` with options-object form reads them.
        event_type => "type",
        bubbles => "bubbles",
        cancelable => "cancelable",
        event_phase => "eventPhase",
        target => "target",
        current_target => "currentTarget",
        time_stamp => "timeStamp",
        composed => "composed",
        is_trusted => "isTrusted",
        default_prevented => "defaultPrevented",
        prevent_default => "preventDefault",
        stop_propagation => "stopPropagation",
        stop_immediate_propagation => "stopImmediatePropagation",
        composed_path => "composedPath",
        capture => "capture",
        once => "once",
        passive => "passive",
        document => "document",
        window => "window",
        navigator => "navigator",
        performance => "performance",
        location => "location",
        history => "history",
        /// `document.readyState` constant — returned every read of the
        /// stub getter.  Pre-interning avoids a per-access StringPool
        /// allocation on what would otherwise be a HashMap lookup path.
        complete => "complete",
        /// `history.scrollRestoration` constant — same rationale as `complete`.
        auto => "auto",
        /// Pre-interned `"about:blank"` for callers that need the default
        /// blank-document URL as a `StringId` without repeating
        /// `strings.intern("about:blank")`.  `NavigationState::new` uses
        /// the `String` form directly; this field ensures the pool entry
        /// exists so that subsequent `intern` calls on the same literal
        /// are HashMap hits rather than fresh insertions.
        about_blank => "about:blank",
        unhandledrejection => "unhandledrejection",
        promise => "promise",
    }

    "Event constructor globals" {
        // `Event` / `CustomEvent` are the global names bound to their
        // respective constructable functions; `detail` is a property key
        // on CustomEvent instances (CustomEventInit dict member + accessor).
        event_global => "Event",
        custom_event_global => "CustomEvent",
        detail => "detail",
    }

    "Specialized Event constructor globals (UIEvent family)" {
        // WebIDL names for the UIEvent family.  Each binds to a
        // constructable function installed during `register_globals` and
        // chains through `UIEvent.prototype → Event.prototype`.
        ui_event_global => "UIEvent",
        mouse_event_global => "MouseEvent",
        keyboard_event_global => "KeyboardEvent",
        focus_event_global => "FocusEvent",
        input_event_global => "InputEvent",
    }

    "UIEvent / MouseEvent / KeyboardEvent init-dict keys" {
        // `view`, plus MouseEvent-specific constructor keys beyond the
        // UA-dispatch Mouse payload set.  `detail` is reused from
        // CustomEvent above; `location` is reused from Window.location.
        view => "view",
        screen_x => "screenX",
        screen_y => "screenY",
        movement_x => "movementX",
        movement_y => "movementY",
    }

    "Non-UIEvent specialized constructor globals" {
        // PromiseRejectionEvent / ErrorEvent / HashChangeEvent /
        // PopStateEvent all chain directly to `Event.prototype` (not
        // UIEvent — they're sibling subclasses of Event).
        promise_rejection_event_global => "PromiseRejectionEvent",
        error_event_global => "ErrorEvent",
        hash_change_event_global => "HashChangeEvent",
        pop_state_event_global => "PopStateEvent",
    }

    "ErrorEvent / PopStateEvent init-dict keys" {
        // `message` / `error` / `reason` / `promise` / `old_url` /
        // `new_url` already exist elsewhere and are reused here.
        filename => "filename",
        lineno => "lineno",
        colno => "colno",
        state => "state",
    }

    "Event payload property keys" {
        // Pre-interned so `create_event_object`'s payload installation
        // can feed them directly into the precomputed-shape slot array
        // without per-dispatch `strings.intern(name)` calls.  Also used
        // by `VmInner::build_precomputed_event_shapes` to walk the
        // shape-transition chain once at `register_globals` time.
        //
        // Shared keys (used by multiple payload variants) are defined
        // once: `alt_key`, `ctrl_key`, `meta_key`, `shift_key`, `data`,
        // `code`, `elapsed_time`, `pseudo_element`, `key`.
        client_x => "clientX",
        client_y => "clientY",
        button => "button",
        buttons => "buttons",
        alt_key => "altKey",
        ctrl_key => "ctrlKey",
        meta_key => "metaKey",
        shift_key => "shiftKey",
        key => "key",
        code => "code",
        repeat => "repeat",
        property_name => "propertyName",
        elapsed_time => "elapsedTime",
        pseudo_element => "pseudoElement",
        animation_name => "animationName",
        input_type => "inputType",
        data => "data",
        is_composing => "isComposing",
        data_type => "dataType",
        related_target => "relatedTarget",
        delta_x => "deltaX",
        delta_y => "deltaY",
        delta_mode => "deltaMode",
        origin => "origin",
        last_event_id => "lastEventId",
        was_clean => "wasClean",
        old_url => "oldURL",
        new_url => "newURL",
        persisted => "persisted",
        old_value => "oldValue",
        new_value => "newValue",
        url => "url",
    }

    "Node / Element accessors" {
        // Pre-interned here because every DOM access touches one of
        // them.  Keeping the `StringId`s in `WellKnownStrings` lets the
        // native getters reach them with a field read rather than a
        // per-call `strings.intern(...)`.
        parent_node => "parentNode",
        parent_element => "parentElement",
        first_child => "firstChild",
        last_child => "lastChild",
        next_sibling => "nextSibling",
        previous_sibling => "previousSibling",
        first_element_child => "firstElementChild",
        last_element_child => "lastElementChild",
        next_element_sibling => "nextElementSibling",
        previous_element_sibling => "previousElementSibling",
        child_nodes => "childNodes",
        children => "children",
        child_element_count => "childElementCount",
        has_child_nodes => "hasChildNodes",
        is_connected => "isConnected",
        contains => "contains",
        node_type => "nodeType",
        node_name => "nodeName",
        node_value => "nodeValue",
        text_content => "textContent",
        tag_name => "tagName",
        id => "id",
        class_name => "className",
        get_attribute => "getAttribute",
        set_attribute => "setAttribute",
        remove_attribute => "removeAttribute",
        has_attribute => "hasAttribute",
        get_attribute_names => "getAttributeNames",
        toggle_attribute => "toggleAttribute",
        append_child => "appendChild",
        remove_child => "removeChild",
        insert_before => "insertBefore",
        replace_child => "replaceChild",
        remove => "remove",
        matches => "matches",
        closest => "closest",
        query_selector => "querySelector",
        query_selector_all => "querySelectorAll",
        clone_node => "cloneNode",
        compare_document_position => "compareDocumentPosition",
        is_same_node => "isSameNode",
        is_equal_node => "isEqualNode",
        owner_document => "ownerDocument",
        get_root_node => "getRootNode",
        normalize => "normalize",
        // Element.prototype.insertAdjacent* (PR4f C4).
        insert_adjacent_element => "insertAdjacentElement",
        insert_adjacent_text => "insertAdjacentText",
        beforebegin => "beforebegin",
        afterbegin => "afterbegin",
        beforeend => "beforeend",
        afterend => "afterend",
        get_elements_by_tag_name => "getElementsByTagName",
        get_elements_by_class_name => "getElementsByClassName",
        // Document RO / RW accessors (PR4f C6 / C7).
        css1_compat => "CSS1Compat",
        // DocumentType.prototype attrs (PR4f C7).
        public_id => "publicId",
        system_id => "systemId",
        // Document collections + stubs (PR4f C7).
        cookie => "cookie",
        referrer => "referrer",
        forms => "forms",
        images => "images",
        links => "links",
        // HTMLElement.prototype method + accessor names (PR5b §C1).
        // `focus` / `blur` install as methods; `activeElement` /
        // `hasFocus` install as document accessor + method
        // respectively.  Pre-interned here so install sites and
        // receiver brand-check helpers share a single StringId.
        focus => "focus",
        blur => "blur",
        // HTMLElement IDL attribute names (PR5b §C2).  Each covers the
        // IDL property identifier; the matching HTML content-attribute
        // name is sometimes identical (lang / title / dir / hidden /
        // nonce / translate / spellcheck / autofocus) and sometimes a
        // case-folded variant (`accessKey` ↔ `accesskey`, `tabIndex` ↔
        // `tabindex`, `inputMode` ↔ `inputmode`, `enterKeyHint` ↔
        // `enterkeyhint`, `contentEditable` ↔ `contenteditable`).
        // WHATWG §3.2.8 / §6.6 / §6.7.  `isContentEditable` is a
        // readonly derived accessor with no backing content attribute.
        access_key => "accessKey",
        tab_index => "tabIndex",
        draggable => "draggable",
        hidden => "hidden",
        lang => "lang",
        dir => "dir",
        title => "title",
        translate => "translate",
        spellcheck => "spellcheck",
        autocapitalize => "autocapitalize",
        input_mode => "inputMode",
        enter_key_hint => "enterKeyHint",
        nonce => "nonce",
        content_editable => "contentEditable",
        is_content_editable => "isContentEditable",
        autofocus => "autofocus",
        // HTMLCollection / NodeList IDL members (PR5b §C3).
        item => "item",
        named_item => "namedItem",
        // NamedNodeMap + Attr IDL members (PR5b §C4 + §C4.5).
        attributes => "attributes",
        get_attribute_node => "getAttributeNode",
        set_attribute_node => "setAttributeNode",
        remove_attribute_node => "removeAttributeNode",
        get_named_item => "getNamedItem",
        set_named_item => "setNamedItem",
        remove_named_item => "removeNamedItem",
        get_named_item_ns => "getNamedItemNS",
        set_named_item_ns => "setNamedItemNS",
        remove_named_item_ns => "removeNamedItemNS",
        owner_element => "ownerElement",
        namespace_uri => "namespaceURI",
        local_name => "localName",
        prefix => "prefix",
        specified => "specified",
        // HTMLIFrameElement.prototype property names (PR4f C8).
        src => "src",
        srcdoc => "srcdoc",
        referrer_policy => "referrerPolicy",
        allow => "allow",
        width => "width",
        height => "height",
        loading => "loading",
        sandbox => "sandbox",
        allow_fullscreen => "allowFullscreen",
        content_document => "contentDocument",
        content_window => "contentWindow",
        // CharacterData (PR4e C5) method names.  `data` / `length` live
        // elsewhere (`data` under event-payload keys above, `length`
        // under core).
        append_data => "appendData",
        insert_data => "insertData",
        delete_data => "deleteData",
        replace_data => "replaceData",
        substring_data => "substringData",
        // Text.prototype (PR4e C5.5)
        split_text => "splitText",
        // ChildNode / ParentNode mixins (PR4e C6 / C7)
        before => "before",
        after => "after",
        replace_with => "replaceWith",
        prepend => "prepend",
        append => "append",
        replace_children => "replaceChildren",
        // `Node.prototype.nodeName` constants for non-Element nodes.
        // Pre-interned so `native_node_get_node_name` returns a cached
        // `StringId` without per-call allocation.
        hash_text => "#text",
        hash_comment => "#comment",
        hash_document => "#document",
        hash_document_fragment => "#document-fragment",
    }

    "AbortController / AbortSignal (PR4d)" {
        // Method, accessor, and listener-option key names.  Pre-interned
        // here so `parse_listener_options` can look up `signal` without
        // re-interning per `addEventListener` call, and so the prototype
        // installer can assemble its property list without re-interning
        // on every VM construction.
        abort_controller => "AbortController",
        abort_signal => "AbortSignal",
        signal => "signal",
        aborted => "aborted",
        abort => "abort",
        onabort => "onabort",
        throw_if_aborted => "throwIfAborted",
        abort_error => "AbortError",
        // EventTarget method names — referenced by both the
        // EventTarget.prototype installer and AbortSignal.prototype's
        // shadowing installer.  Pre-interning here means each prototype
        // installer hits an existing pool entry instead of allocating.
        add_event_listener => "addEventListener",
        remove_event_listener => "removeEventListener",
        dispatch_event => "dispatchEvent",
    }

    "DOMException" {
        // The constructor identifier, WebIDL member names, and the
        // subset of WHATWG §2.1 spec exception names currently used.
        // Additional names land at their first use site (interning is
        // deduplicating, so a later `well_known` entry is a
        // HashMap-hit fallback for hot paths).
        dom_exception => "DOMException",
        dom_exc_syntax_error => "SyntaxError",
        dom_exc_hierarchy_request_error => "HierarchyRequestError",
        dom_exc_not_found_error => "NotFoundError",
        dom_exc_wrong_document_error => "WrongDocumentError",
        dom_exc_invalid_state_error => "InvalidStateError",
        dom_exc_timeout_error => "TimeoutError",
        dom_exc_data_clone_error => "DataCloneError",
    }

    "Headers (WHATWG Fetch §5.2)" {
        // Method and iteration-helper names.  `get` / `set` / `append` /
        // `value` / `key` already live elsewhere and are reused here.
        // `delete` is an ES keyword — field named `delete_str` to
        // sidestep the `r#delete` raw-identifier contortion.
        headers_global => "Headers",
        headers => "headers",
        delete_str => "delete",
        has => "has",
        get_set_cookie => "getSetCookie",
        for_each => "forEach",
        entries => "entries",
        keys => "keys",
        values => "values",
        set_cookie_header => "set-cookie",
    }

    "Request / Response (WHATWG Fetch §5.3 / §5.5)" {
        // Globals + IDL attr names + static factory method names +
        // enum strings.  `url` / `headers` already live above and are
        // reused here.
        request => "Request",
        response => "Response",
        method => "method",
        body => "body",
        body_used => "bodyUsed",
        ok => "ok",
        status_text => "statusText",
        redirected => "redirected",
        redirect => "redirect",
        mode => "mode",
        credentials => "credentials",
        cache => "cache",
        clone => "clone",
        json => "json",
        // Method / response-type string constants — pre-interned so
        // per-instance `.type` / `.method` accessor reads return the
        // pool entry directly.
        http_get => "GET",
        http_head => "HEAD",
        http_post => "POST",
        http_put => "PUT",
        http_delete => "DELETE",
        http_options => "OPTIONS",
        http_patch => "PATCH",
        http_connect => "CONNECT",
        http_trace => "TRACE",
        content_type => "content-type",
        application_json_utf8 => "application/json",
        text_plain_charset_utf8 => "text/plain;charset=UTF-8",
        response_type_default => "default",
        response_type_basic => "basic",
        response_type_cors => "cors",
        response_type_error => "error",
        response_type_opaque => "opaque",
        response_type_opaqueredirect => "opaqueredirect",
    }

    "ArrayBuffer / Blob / Body mixin (ES2020 §24.1 / File API §3 / WHATWG Fetch §5 Body mixin)" {
        // Constructor global names are separate fields from the
        // camelCase attribute / method names to sidestep the name
        // collision the Headers ctor ran into (`"Headers"` ctor name
        // vs `"headers"` attr name).
        array_buffer_global => "ArrayBuffer",
        blob_global => "Blob",
        byte_length => "byteLength",
        size => "size",
        slice => "slice",
        text => "text",
        array_buffer => "arrayBuffer",
    }

    "TypedArray + DataView (ES2024 §23.2 / §25.3)" {
        // Constructor name StringIds.  `data_view_global` and the 11
        // concrete-subclass entries back the real globals; the abstract
        // `%TypedArray%` intrinsic has no globalThis binding per
        // §23.2.2 so no StringId is needed for it.  All are interned
        // eagerly so `register_typed_array_subclass` can fetch them
        // without a per-call `strings.intern(...)` round-trip.
        data_view_global => "DataView",
        int8_array_global => "Int8Array",
        uint8_array_global => "Uint8Array",
        uint8_clamped_array_global => "Uint8ClampedArray",
        int16_array_global => "Int16Array",
        uint16_array_global => "Uint16Array",
        int32_array_global => "Int32Array",
        uint32_array_global => "Uint32Array",
        float32_array_global => "Float32Array",
        float64_array_global => "Float64Array",
        bigint64_array_global => "BigInt64Array",
        biguint64_array_global => "BigUint64Array",
        buffer => "buffer",
        byte_offset => "byteOffset",
        bytes_per_element => "BYTES_PER_ELEMENT",
    }

    "%TypedArray%.prototype method names" {
        // Pre-interned so `install_typed_array_prototype_members`
        // skips the per-method `strings.intern(...)` round-trip
        // during `Vm::new`.  `slice` / `set` / `values` / `keys` /
        // `entries` / `for_each` / `join` are reused from the
        // Headers / Body / Array sections above.
        fill => "fill",
        subarray => "subarray",
        copy_within => "copyWithin",
        reverse => "reverse",
        index_of => "indexOf",
        last_index_of => "lastIndexOf",
        includes => "includes",
        at => "at",
        every => "every",
        some => "some",
        find => "find",
        find_index => "findIndex",
        find_last => "findLast",
        find_last_index => "findLastIndex",
        map => "map",
        filter => "filter",
        reduce => "reduce",
        reduce_right => "reduceRight",
        sort => "sort",
        flat_map => "flatMap",
        to_locale_string => "toLocaleString",
    }

    "DataView.prototype method names" {
        // Pre-interned so `install_data_view_members` skips the
        // per-method `strings.intern(...)` round-trip during
        // `Vm::new`.  All 20 get* / set* names are unique to
        // DataView and have no overlap with reusable identifiers
        // above.
        get_int8 => "getInt8",
        get_uint8 => "getUint8",
        get_int16 => "getInt16",
        get_uint16 => "getUint16",
        get_int32 => "getInt32",
        get_uint32 => "getUint32",
        get_float32 => "getFloat32",
        get_float64 => "getFloat64",
        get_bigint64 => "getBigInt64",
        get_biguint64 => "getBigUint64",
        set_int8 => "setInt8",
        set_uint8 => "setUint8",
        set_int16 => "setInt16",
        set_uint16 => "setUint16",
        set_int32 => "setInt32",
        set_uint32 => "setUint32",
        set_float32 => "setFloat32",
        set_float64 => "setFloat64",
        set_bigint64 => "setBigInt64",
        set_biguint64 => "setBigUint64",
    }

    "TextEncoder / TextDecoder (WHATWG Encoding §8)" {
        // Constructor globals use the `*_global` suffix convention.
        // Method / attribute names are separate fields: `encoding`
        // doubles as the `TextDecoder.prototype.encoding` getter name
        // and an options-bag key, so the StringId is shared.
        text_encoder_global => "TextEncoder",
        text_decoder_global => "TextDecoder",
        encode => "encode",
        encode_into => "encodeInto",
        decode => "decode",
        encoding => "encoding",
        fatal => "fatal",
        ignore_bom => "ignoreBOM",
        read => "read",
        written => "written",
        stream => "stream",
        utf_8 => "utf-8",
        utf_16le => "utf-16le",
        utf_16be => "utf-16be",
    }

    "URLSearchParams / FormData (WHATWG URL §6 / XHR §4.3)" {
        // Constructor globals + method / accessor names that are
        // unique to these two interfaces.  `append` / `delete_str` /
        // `get` / `has` / `set` / `for_each` / `keys` / `values` /
        // `entries` / `sort` are reused from earlier sections.
        url_search_params_global => "URLSearchParams",
        form_data_global => "FormData",
        get_all => "getAll",
        to_string_method => "toString",
        application_form_urlencoded =>
            "application/x-www-form-urlencoded;charset=UTF-8",
        multipart_form_data_prefix => "multipart/form-data; boundary=",
        // Default filename used when a `Blob` (not a `File`) is appended
        // without an explicit filename argument — matches WHATWG XHR
        // §4.3 step "create an entry" and Chromium / Firefox behaviour.
        blob_default_filename => "blob",
    }

    "ReadableStream (WHATWG Streams §4)" {
        // Constructor globals + method / accessor names unique to
        // the streams surface.  `read` / `value` / `done` /
        // `reason` / `size` / `stream` / `byte_length` already
        // live above and are reused here; `cancel` is introduced
        // in this section because it has no prior call site outside
        // the streams API.
        readable_stream_global => "ReadableStream",
        readable_stream_default_reader_global => "ReadableStreamDefaultReader",
        readable_stream_default_controller_global =>
            "ReadableStreamDefaultController",
        count_queuing_strategy_global => "CountQueuingStrategy",
        byte_length_queuing_strategy_global => "ByteLengthQueuingStrategy",
        start => "start",
        pull => "pull",
        cancel => "cancel",
        high_water_mark => "highWaterMark",
        get_reader => "getReader",
        release_lock => "releaseLock",
        desired_size => "desiredSize",
        enqueue => "enqueue",
        close => "close",
        locked_attr => "locked",
        closed_attr => "closed",
    }
}

/// Well-known symbol IDs, allocated at VM creation.
#[allow(dead_code)]
pub(crate) struct WellKnownSymbols {
    pub(crate) iterator: SymbolId,
    pub(crate) async_iterator: SymbolId,
    pub(crate) has_instance: SymbolId,
    pub(crate) to_primitive: SymbolId,
    pub(crate) to_string_tag: SymbolId,
    pub(crate) species: SymbolId,
    pub(crate) is_concat_spreadable: SymbolId,
}

impl WellKnownSymbols {
    /// Allocate the 7 well-known Symbol records at fixed SymbolIds 0-6
    /// and return the populated table alongside the symbol Vec (which
    /// the caller stores on `VmInner.symbols`).  Returning the Vec
    /// avoids a second `SymbolId` round-trip during VM construction —
    /// the caller moves it straight into the field.
    pub(crate) fn alloc_all(strings: &mut StringPool) -> (Self, Vec<SymbolRecord>) {
        let mut symbols = Vec::new();
        let mut alloc = |desc: &str| -> SymbolId {
            let id = SymbolId(symbols.len() as u32);
            symbols.push(SymbolRecord {
                description: Some(strings.intern(desc)),
            });
            id
        };
        let well_known = Self {
            iterator: alloc("Symbol.iterator"),
            async_iterator: alloc("Symbol.asyncIterator"),
            has_instance: alloc("Symbol.hasInstance"),
            to_primitive: alloc("Symbol.toPrimitive"),
            to_string_tag: alloc("Symbol.toStringTag"),
            species: alloc("Symbol.species"),
            is_concat_spreadable: alloc("Symbol.isConcatSpreadable"),
        };
        (well_known, symbols)
    }
}
