//! Pre-interned string IDs and well-known Symbol IDs, built once at
//! `Vm::new` time and consulted on every property operation,
//! identifier comparison, and event-object construction.
//!
//! Split out of `mod.rs` to keep that file under the project's
//! 1000-line convention.  The structs themselves are passive data
//! (fields are `Copy` newtypes) — the only behaviour here is the
//! `new` constructors that pre-intern each name on the crate's
//! `StringPool` / `SymbolRecord` table.
//!
//! ## `WellKnownStrings` shape
//!
//! Field declarations and intern-time literals are unified through
//! the [`define_well_known_strings!`] macro: each `field => "literal"`
//! pair is the **single source of truth** for both the
//! `WellKnownStrings` struct field and its
//! `WellKnownStrings::intern_all` initialiser.  Eliminates the
//! prior 388-pair manual sync surface (a typo in the literal that
//! diverged from the field name was an undetectable runtime bug;
//! now the two sides cannot drift).
//!
//! Sections are grouped by spec area; each `"section name" { … }`
//! block is purely a navigation marker (the macro discards the
//! string at expansion time, so it carries no runtime cost).

use super::pools::StringPool;
use super::value::{StringId, SymbolId, SymbolRecord};

/// Declarative macro that emits both the `WellKnownStrings` struct
/// and its `intern_all` initialiser from a single ordered list of
/// `field => "literal"` pairs.  See module docs for the rationale.
///
/// The `"section name" { ... }` blocks act as navigation markers
/// in the source — the macro consumes the literal but doesn't emit
/// it (so no per-section runtime overhead).  Each field accepts an
/// optional `$(#[$attr:meta])*` attribute prefix which gets emitted
/// on the generated struct field — `///` rustdoc comments work as
/// `#[doc = "..."]` attrs and survive the expansion intact.  Plain
/// `//` line comments inside the macro invocation are stripped at
/// parse time (transparent to the expansion) and serve as inline
/// rationale for human readers.  Pure declarative macro_rules; no
/// proc-macro infrastructure needed.
macro_rules! define_well_known_strings {
    (
        $(
            $_section:literal {
                $(
                    $(#[$attr:meta])*
                    $field:ident => $literal:literal
                ),* $(,)?
            }
        )*
    ) => {
        /// Frequently used interned string IDs, cached at VM creation.
        ///
        /// Generated by [`define_well_known_strings!`] — see module
        /// docs for the rationale.  Field names and intern literals
        /// share a single source of truth in the macro invocation
        /// below, so no `field`/`literal` divergence is possible.
        #[allow(dead_code)] // Fields used by interpreter and future built-ins.
        pub(crate) struct WellKnownStrings {
            $($(
                $(#[$attr])*
                pub(crate) $field: StringId,
            )*)*
        }

        impl WellKnownStrings {
            /// Intern every well-known name on `strings` and return
            /// the populated table.  Must be the only caller to
            /// populate `WellKnownStrings` — the fields carry
            /// expectations (e.g. `empty` is literally `intern("")`)
            /// that other VM code relies on without re-checking.
            pub(crate) fn intern_all(strings: &mut StringPool) -> Self {
                Self {
                    $($( $field: strings.intern($literal), )*)*
                }
            }
        }
    };
}

define_well_known_strings! {
    "core" {
        undefined => "undefined",
        null => "null",
        r#true => "true",
        r#false => "false",
        nan => "NaN",
        infinity => "Infinity",
        neg_infinity => "-Infinity",
        zero => "0",
        empty => "",
        prototype => "prototype",
        constructor => "constructor",
        length => "length",
        name => "name",
        message => "message",
        log => "log",
        error => "error",
        warn => "warn",
        object_type => "object",
        boolean_type => "boolean",
        number_type => "number",
        string_type => "string",
        function_type => "function",
        symbol_type => "symbol",
        bigint_type => "bigint",
        object_to_string => "[object Object]",
        next => "next",
        value => "value",
        done => "done",
        return_str => "return",
        last_index => "lastIndex",
        index => "index",
        input => "input",
        join => "join",
        to_json => "toJSON",
        // Pre-interned so the OrdinaryToPrimitive (§7.1.1.1) hot path
        // in `vm/ops.rs::to_primitive` skips the `strings.intern("valueOf")`
        // hashmap lookup on every plain-Object coercion.  Companion to
        // `to_string_method` declared further below.
        value_of => "valueOf",
        get => "get",
        set => "set",
        enumerable => "enumerable",
        configurable => "configurable",
        writable => "writable",
        source => "source",
        /// `MessageEvent.ports` — pre-interned so the postMessage
        /// shape extension picks the StringId out of `WellKnownStrings`
        /// instead of round-tripping through `strings.intern("ports")`
        /// per dispatched event.
        ports => "ports",
        flags => "flags",
        status => "status",
        fulfilled => "fulfilled",
        rejected => "rejected",
        reason => "reason",
        errors => "errors",
        aggregate_error => "AggregateError",
    }

    "Event-dispatch identifiers (PR3)" {
        // Property names installed on every event object — pre-interned
        // here to avoid a HashMap lookup per name per dispatch.  Listener
        // option keys (`capture`/`once`/`passive`) live here too since
        // every `addEventListener` with options-object form reads them.
        event_type => "type",
        bubbles => "bubbles",
        cancelable => "cancelable",
        event_phase => "eventPhase",
        target => "target",
        current_target => "currentTarget",
        time_stamp => "timeStamp",
        composed => "composed",
        is_trusted => "isTrusted",
        default_prevented => "defaultPrevented",
        prevent_default => "preventDefault",
        stop_propagation => "stopPropagation",
        stop_immediate_propagation => "stopImmediatePropagation",
        composed_path => "composedPath",
        capture => "capture",
        once => "once",
        passive => "passive",
        document => "document",
        window => "window",
        navigator => "navigator",
        performance => "performance",
        location => "location",
        history => "history",
        /// `document.readyState` constant — returned every read of the
        /// stub getter.  Pre-interning avoids a per-access StringPool
        /// allocation on what would otherwise be a HashMap lookup path.
        complete => "complete",
        /// `history.scrollRestoration` constant — same rationale as `complete`.
        auto => "auto",
        /// Pre-interned `"about:blank"` for callers that need the default
        /// blank-document URL as a `StringId` without repeating
        /// `strings.intern("about:blank")`.  `NavigationState::new` uses
        /// the `String` form directly; this field ensures the pool entry
        /// exists so that subsequent `intern` calls on the same literal
        /// are HashMap hits rather than fresh insertions.
        about_blank => "about:blank",
        unhandledrejection => "unhandledrejection",
        promise => "promise",
    }

    "Event constructor globals" {
        // `Event` / `CustomEvent` are the global names bound to their
        // respective constructable functions; `detail` is a property key
        // on CustomEvent instances (CustomEventInit dict member + accessor).
        event_global => "Event",
        custom_event_global => "CustomEvent",
        detail => "detail",
    }

    "Specialized Event constructor globals (UIEvent family)" {
        // WebIDL names for the UIEvent family.  Each binds to a
        // constructable function installed during `register_globals` and
        // chains through `UIEvent.prototype → Event.prototype`.
        ui_event_global => "UIEvent",
        mouse_event_global => "MouseEvent",
        keyboard_event_global => "KeyboardEvent",
        focus_event_global => "FocusEvent",
        input_event_global => "InputEvent",
    }

    "UIEvent / MouseEvent / KeyboardEvent init-dict keys" {
        // `view`, plus MouseEvent-specific constructor keys beyond the
        // UA-dispatch Mouse payload set.  `detail` is reused from
        // CustomEvent above; `location` is reused from Window.location.
        view => "view",
        screen_x => "screenX",
        screen_y => "screenY",
        movement_x => "movementX",
        movement_y => "movementY",
    }

    "Non-UIEvent specialized constructor globals" {
        // PromiseRejectionEvent / ErrorEvent / HashChangeEvent /
        // PopStateEvent all chain directly to `Event.prototype` (not
        // UIEvent — they're sibling subclasses of Event).
        // AnimationEvent / TransitionEvent / CloseEvent (M4-12 slot
        // #11a) join the same family — sibling subclasses of Event,
        // installed via the shared `register_event_subclass` helper.
        promise_rejection_event_global => "PromiseRejectionEvent",
        error_event_global => "ErrorEvent",
        hash_change_event_global => "HashChangeEvent",
        pop_state_event_global => "PopStateEvent",
        animation_event_global => "AnimationEvent",
        transition_event_global => "TransitionEvent",
        close_event_global => "CloseEvent",
    }

    "ErrorEvent / PopStateEvent init-dict keys" {
        // `message` / `error` / `reason` / `promise` / `old_url` /
        // `new_url` already exist elsewhere and are reused here.
        filename => "filename",
        lineno => "lineno",
        colno => "colno",
        state => "state",
    }

    "Event payload property keys" {
        // Pre-interned so `create_event_object`'s payload installation
        // can feed them directly into the precomputed-shape slot array
        // without per-dispatch `strings.intern(name)` calls.  Also used
        // by `VmInner::build_precomputed_event_shapes` to walk the
        // shape-transition chain once at `register_globals` time.
        //
        // Shared keys (used by multiple payload variants) are defined
        // once: `alt_key`, `ctrl_key`, `meta_key`, `shift_key`, `data`,
        // `code`, `elapsed_time`, `pseudo_element`, `key`.
        client_x => "clientX",
        client_y => "clientY",
        button => "button",
        buttons => "buttons",
        alt_key => "altKey",
        ctrl_key => "ctrlKey",
        meta_key => "metaKey",
        shift_key => "shiftKey",
        key => "key",
        code => "code",
        repeat => "repeat",
        property_name => "propertyName",
        elapsed_time => "elapsedTime",
        pseudo_element => "pseudoElement",
        animation_name => "animationName",
        input_type => "inputType",
        data => "data",
        is_composing => "isComposing",
        data_type => "dataType",
        related_target => "relatedTarget",
        delta_x => "deltaX",
        delta_y => "deltaY",
        delta_mode => "deltaMode",
        origin => "origin",
        last_event_id => "lastEventId",
        was_clean => "wasClean",
        old_url => "oldURL",
        new_url => "newURL",
        persisted => "persisted",
        old_value => "oldValue",
        new_value => "newValue",
        url => "url",
    }

    "Node / Element accessors" {
        // Pre-interned here because every DOM access touches one of
        // them.  Keeping the `StringId`s in `WellKnownStrings` lets the
        // native getters reach them with a field read rather than a
        // per-call `strings.intern(...)`.
        parent_node => "parentNode",
        parent_element => "parentElement",
        first_child => "firstChild",
        last_child => "lastChild",
        next_sibling => "nextSibling",
        previous_sibling => "previousSibling",
        first_element_child => "firstElementChild",
        last_element_child => "lastElementChild",
        next_element_sibling => "nextElementSibling",
        previous_element_sibling => "previousElementSibling",
        child_nodes => "childNodes",
        children => "children",
        child_element_count => "childElementCount",
        has_child_nodes => "hasChildNodes",
        is_connected => "isConnected",
        contains => "contains",
        node_type => "nodeType",
        node_name => "nodeName",
        node_value => "nodeValue",
        text_content => "textContent",
        tag_name => "tagName",
        id => "id",
        class_name => "className",
        get_attribute => "getAttribute",
        set_attribute => "setAttribute",
        remove_attribute => "removeAttribute",
        has_attribute => "hasAttribute",
        get_attribute_names => "getAttributeNames",
        toggle_attribute => "toggleAttribute",
        append_child => "appendChild",
        remove_child => "removeChild",
        insert_before => "insertBefore",
        replace_child => "replaceChild",
        remove => "remove",
        matches => "matches",
        closest => "closest",
        query_selector => "querySelector",
        query_selector_all => "querySelectorAll",
        clone_node => "cloneNode",
        compare_document_position => "compareDocumentPosition",
        is_same_node => "isSameNode",
        is_equal_node => "isEqualNode",
        owner_document => "ownerDocument",
        get_root_node => "getRootNode",
        normalize => "normalize",
        // Element.prototype.insertAdjacent* (PR4f C4).
        insert_adjacent_element => "insertAdjacentElement",
        insert_adjacent_text => "insertAdjacentText",
        beforebegin => "beforebegin",
        afterbegin => "afterbegin",
        beforeend => "beforeend",
        afterend => "afterend",
        get_elements_by_tag_name => "getElementsByTagName",
        get_elements_by_class_name => "getElementsByClassName",
        // Document RO / RW accessors (PR4f C6 / C7).
        css1_compat => "CSS1Compat",
        // DocumentType.prototype attrs (PR4f C7).
        public_id => "publicId",
        system_id => "systemId",
        // Document collections + stubs (PR4f C7).
        cookie => "cookie",
        referrer => "referrer",
        forms => "forms",
        images => "images",
        links => "links",
        // HTMLElement.prototype method + accessor names (PR5b §C1).
        // `focus` / `blur` install as methods; `activeElement` /
        // `hasFocus` install as document accessor + method
        // respectively.  Pre-interned here so install sites and
        // receiver brand-check helpers share a single StringId.
        focus => "focus",
        blur => "blur",
        // HTMLElement IDL attribute names (PR5b §C2).  Each covers the
        // IDL property identifier; the matching HTML content-attribute
        // name is sometimes identical (lang / title / dir / hidden /
        // nonce / translate / spellcheck / autofocus) and sometimes a
        // case-folded variant (`accessKey` ↔ `accesskey`, `tabIndex` ↔
        // `tabindex`, `inputMode` ↔ `inputmode`, `enterKeyHint` ↔
        // `enterkeyhint`, `contentEditable` ↔ `contenteditable`).
        // WHATWG §3.2.8 / §6.6 / §6.7.  `isContentEditable` is a
        // readonly derived accessor with no backing content attribute.
        access_key => "accessKey",
        tab_index => "tabIndex",
        draggable => "draggable",
        hidden => "hidden",
        lang => "lang",
        dir => "dir",
        title => "title",
        translate => "translate",
        spellcheck => "spellcheck",
        autocapitalize => "autocapitalize",
        input_mode => "inputMode",
        enter_key_hint => "enterKeyHint",
        nonce => "nonce",
        content_editable => "contentEditable",
        is_content_editable => "isContentEditable",
        autofocus => "autofocus",
        // HTMLCollection / NodeList IDL members (PR5b §C3).
        item => "item",
        named_item => "namedItem",
        // NamedNodeMap + Attr IDL members (PR5b §C4 + §C4.5).
        attributes => "attributes",
        get_attribute_node => "getAttributeNode",
        set_attribute_node => "setAttributeNode",
        remove_attribute_node => "removeAttributeNode",
        get_named_item => "getNamedItem",
        set_named_item => "setNamedItem",
        remove_named_item => "removeNamedItem",
        get_named_item_ns => "getNamedItemNS",
        set_named_item_ns => "setNamedItemNS",
        remove_named_item_ns => "removeNamedItemNS",
        owner_element => "ownerElement",
        namespace_uri => "namespaceURI",
        local_name => "localName",
        prefix => "prefix",
        specified => "specified",
        // HTMLIFrameElement.prototype property names (PR4f C8).
        src => "src",
        srcdoc => "srcdoc",
        referrer_policy => "referrerPolicy",
        allow => "allow",
        width => "width",
        height => "height",
        loading => "loading",
        sandbox => "sandbox",
        allow_fullscreen => "allowFullscreen",
        content_document => "contentDocument",
        content_window => "contentWindow",
        // CharacterData (PR4e C5) method names.  `data` / `length` live
        // elsewhere (`data` under event-payload keys above, `length`
        // under core).
        append_data => "appendData",
        insert_data => "insertData",
        delete_data => "deleteData",
        replace_data => "replaceData",
        substring_data => "substringData",
        // Text.prototype (PR4e C5.5)
        split_text => "splitText",
        // ChildNode / ParentNode mixins (PR4e C6 / C7)
        before => "before",
        after => "after",
        replace_with => "replaceWith",
        prepend => "prepend",
        append => "append",
        replace_children => "replaceChildren",
        // `Node.prototype.nodeName` constants for non-Element nodes.
        // Pre-interned so `native_node_get_node_name` returns a cached
        // `StringId` without per-call allocation.
        hash_text => "#text",
        hash_comment => "#comment",
        hash_document => "#document",
        hash_document_fragment => "#document-fragment",
    }

    "MutationObserver (slot #11-mutation-observer)" {
        // Constructor global + method names (`disconnect` is unique
        // here; `observe` is unique to observer surfaces and only
        // referenced from this file going forward).
        // `MutationObserverInit` dictionary keys + `MutationRecord`
        // shape keys are pre-interned so each
        // `parse_mutation_observer_init` field read and each
        // `mutation_record_to_js` property write avoids a per-call
        // `strings.intern(...)` round-trip.  WHATWG DOM §4.3.
        // `target` / `attributes` / `next_sibling` /
        // `previous_sibling` / `old_value` already live in earlier
        // sections and are reused here.
        mutation_observer_global => "MutationObserver",
        observe => "observe",
        disconnect => "disconnect",
        take_records => "takeRecords",
        child_list => "childList",
        character_data => "characterData",
        subtree => "subtree",
        attribute_old_value => "attributeOldValue",
        character_data_old_value => "characterDataOldValue",
        attribute_filter => "attributeFilter",
        added_nodes => "addedNodes",
        removed_nodes => "removedNodes",
        attribute_name => "attributeName",
    }

    "D-10 events-misc constructor globals + init-dict keys (slot #11-events-misc)" {
        // 10 NEW Event-family constructor globals.  All chain through
        // either `Event.prototype` (8 of them) or `MouseEvent.prototype`
        // (WheelEvent only) / `UIEvent.prototype` (CompositionEvent
        // only).  Installed via the shared `register_event_subclass`
        // helper (Event-base) or `register_descendant` (UIEvent-base
        // family).
        submit_event_global => "SubmitEvent",
        formdata_event_global => "FormDataEvent",
        toggle_event_global => "ToggleEvent",
        composition_event_global => "CompositionEvent",
        clipboard_event_global => "ClipboardEvent",
        progress_event_global => "ProgressEvent",
        before_unload_event_global => "BeforeUnloadEvent",
        message_event_global => "MessageEvent",
        wheel_event_global => "WheelEvent",
        page_transition_event_global => "PageTransitionEvent",
        // Init-dict / IDL attribute keys not already in earlier sections.
        // Keys reused from elsewhere: `data` (composition), `origin` /
        // `last_event_id` / `source` / `ports` (message), `persisted`
        // (page_transition), `delta_x` / `delta_y` / `delta_mode`
        // (wheel), `toggle` (existing event-type SID reused for
        // ToggleEvent's `type` value).
        submitter => "submitter",
        form_data => "formData",
        old_state => "oldState",
        new_state => "newState",
        clipboard_data => "clipboardData",
        length_computable => "lengthComputable",
        loaded => "loaded",
        total => "total",
        return_value => "returnValue",
        data_transfer => "dataTransfer",
        target_ranges => "targetRanges",
        get_target_ranges => "getTargetRanges",
        // WheelEvent-specific deltaZ + DOM_DELTA_* constant names.
        // `deltaX` / `deltaY` / `deltaMode` already in event-payload
        // section.
        delta_z => "deltaZ",
        dom_delta_pixel => "DOM_DELTA_PIXEL",
        dom_delta_line => "DOM_DELTA_LINE",
        dom_delta_page => "DOM_DELTA_PAGE",
    }

    "D-9 events-modern-input constructor globals + init-dict keys (slot #11-events-modern-input)" {
        // PointerEvent + DragEvent + Touch family + DataTransfer family
        // constructor globals.  Reused SIDs from earlier sections:
        // `target`, `screen_x/y`, `client_x/y`, `width`, `height`,
        // `files`, `data_transfer` (the IDL attribute name),
        // `add` / `remove` / `clear_method` / `item` / `length` /
        // `kind` (NEW below for DataTransferItem.kind).
        pointer_event_global => "PointerEvent",
        drag_event_global => "DragEvent",
        touch_event_global => "TouchEvent",
        touch_global => "Touch",
        touch_list_global => "TouchList",
        data_transfer_global => "DataTransfer",
        data_transfer_item_global => "DataTransferItem",
        data_transfer_item_list_global => "DataTransferItemList",
        // PointerEventInit / PointerEvent IDL members (UI Events
        // Pointer §6 — extends MouseEventInit).
        pointer_id => "pointerId",
        pressure => "pressure",
        tangential_pressure => "tangentialPressure",
        tilt_x => "tiltX",
        tilt_y => "tiltY",
        twist => "twist",
        altitude_angle => "altitudeAngle",
        azimuth_angle => "azimuthAngle",
        pointer_type => "pointerType",
        is_primary => "isPrimary",
        coalesced_events => "coalescedEvents",
        predicted_events => "predictedEvents",
        get_coalesced_events => "getCoalescedEvents",
        get_predicted_events => "getPredictedEvents",
        // TouchInit / Touch IDL members (Touch Events §5).
        // `target` / `screen_x` / `screen_y` / `client_x` /
        // `client_y` reused from earlier sections.
        identifier => "identifier",
        page_x => "pageX",
        page_y => "pageY",
        radius_x => "radiusX",
        radius_y => "radiusY",
        rotation_angle => "rotationAngle",
        force => "force",
        // TouchEventInit / TouchEvent IDL members.
        touches => "touches",
        target_touches => "targetTouches",
        changed_touches => "changedTouches",
        // DataTransfer IDL members (HTML DnD §6.2).  `types` /
        // `items` / `files` (existing) are accessor names.
        drop_effect => "dropEffect",
        effect_allowed => "effectAllowed",
        items => "items",
        types => "types",
        get_data => "getData",
        set_data => "setData",
        clear_data => "clearData",
        set_drag_image => "setDragImage",
        // DataTransferItem / DataTransferItemList IDL members.
        // `kind` is unique to DataTransferItem in the workspace —
        // not yet present in any earlier section.
        kind => "kind",
        get_as_string => "getAsString",
        get_as_file => "getAsFile",
        // String literals returned by `DataTransferItem.kind` (per
        // HTML §6.3 — exactly `"string"` or `"file"`).  Pre-interned
        // so the kind getter avoids a per-call `strings.intern`.
        kind_string => "string",
        kind_file => "file",
        // String literal used for `DataTransfer.types` Files entry
        // when any file-kind item is present (HTML §6.2 step 3-5).
        types_files_entry => "Files",
    }

    "Storage / StorageEvent (slot #11-storage-web)" {
        // Constructor / global identifier names (WHATWG HTML §11.2).
        // `localStorage` / `sessionStorage` are accessor properties
        // installed on `Window.prototype` (matching the
        // `[SameObject]` semantics of the Storage interface — the
        // getter returns a single cached wrapper per area).
        local_storage_global => "localStorage",
        session_storage_global => "sessionStorage",
        storage_global => "Storage",
        storage_event_global => "StorageEvent",
        // Method names on `Storage.prototype`.  `clear` / `key` /
        // `length` are reused from earlier sections.
        get_item => "getItem",
        set_item => "setItem",
        remove_item => "removeItem",
        clear_method => "clear",
        // `StorageEvent` IDL attribute name not already present.
        // `key` / `oldValue` / `newValue` / `url` already live in
        // earlier sections and are reused here.
        storage_area => "storageArea",
        // DOMException name surfaced when `setItem` exceeds the
        // 5 MiB origin quota (WHATWG HTML §11.2.1 +
        // `StorageError::quota_exceeded` round-trip).  Pre-interned
        // here so the `vm/host/storage.rs` quota path can produce
        // the DOMException without a per-call `strings.intern(...)`.
        dom_exc_quota_exceeded_error => "QuotaExceededError",
    }

    "DOMTokenList / DOMStringMap (slot #11-classlist-dataset)" {
        // `Element.classList` (DOMTokenList) accessor + method names.
        // `length` / `value` / `item` / `contains` already live in the
        // core/Element-children sections above and are reused here —
        // pre-interning the new identifiers keeps method install + JS
        // dispatch on a single StringId per name.  WHATWG DOM §3.5 / §7.1.
        class_list => "classList",
        add => "add",
        toggle => "toggle",
        replace => "replace",
        supports => "supports",
        // `HTMLElement.dataset` (DOMStringMap) accessor name.  Named-
        // property exotic semantics dispatch through ObjectKind, so no
        // per-method identifier is needed beyond the accessor name.
        // WHATWG HTML §3.2.6 / WebIDL §3.10.
        dataset => "dataset",
    }

    "CSSStyleDeclaration / CSS namespace (slot #11-style-declaration)" {
        // `Element.style` accessor — returns an identity-cached
        // `CSSStyleDeclaration` (Inline source) wrapper. CSSOM §6.6.
        style => "style",
        // `CSSStyleDeclaration` accessor + method names.  `length` /
        // `item` already live in the core/Element-children sections.
        css_text => "cssText",
        get_property_value => "getPropertyValue",
        get_property_priority => "getPropertyPriority",
        set_property => "setProperty",
        remove_property => "removeProperty",
        parent_rule => "parentRule",
        // `window.getComputedStyle` global function name.  CSSOM §7.2.
        get_computed_style => "getComputedStyle",
        // CSS namespace static methods (CSSOM §6.7).  `escape` /
        // `supports` (the latter shared with DOMTokenList) plus the
        // `CSS` namespace identifier.
        css_namespace => "CSS",
        escape => "escape",
        // CSSStyleSheet / CSSRuleList / CSSStyleRule / StyleSheetList
        // surface (PR-B).  CSSOM §6.2 / §6.3 / §6.6 / §6.8.
        sheet => "sheet",
        css_rules => "cssRules",
        owner_node => "ownerNode",
        r#type => "type",
        insert_rule => "insertRule",
        delete_rule => "deleteRule",
        selector_text => "selectorText",
        parent_style_sheet => "parentStyleSheet",
        style_sheets => "styleSheets",
    }

    "AbortController / AbortSignal (PR4d)" {
        // Method, accessor, and listener-option key names.  Pre-interned
        // here so `parse_listener_options` can look up `signal` without
        // re-interning per `addEventListener` call, and so the prototype
        // installer can assemble its property list without re-interning
        // on every VM construction.
        abort_controller => "AbortController",
        abort_signal => "AbortSignal",
        signal => "signal",
        aborted => "aborted",
        abort => "abort",
        onabort => "onabort",
        throw_if_aborted => "throwIfAborted",
        abort_error => "AbortError",
        // EventTarget method names — referenced by both the
        // EventTarget.prototype installer and AbortSignal.prototype's
        // shadowing installer.  Pre-interning here means each prototype
        // installer hits an existing pool entry instead of allocating.
        add_event_listener => "addEventListener",
        remove_event_listener => "removeEventListener",
        dispatch_event => "dispatchEvent",
    }

    "DOMException" {
        // The constructor identifier, WebIDL member names, and the
        // subset of WHATWG §2.1 spec exception names currently used.
        // Additional names land at their first use site (interning is
        // deduplicating, so a later `well_known` entry is a
        // HashMap-hit fallback for hot paths).
        dom_exception => "DOMException",
        dom_exc_syntax_error => "SyntaxError",
        dom_exc_hierarchy_request_error => "HierarchyRequestError",
        dom_exc_not_found_error => "NotFoundError",
        dom_exc_wrong_document_error => "WrongDocumentError",
        dom_exc_invalid_state_error => "InvalidStateError",
        dom_exc_timeout_error => "TimeoutError",
        dom_exc_data_clone_error => "DataCloneError",
        dom_exc_index_size_error => "IndexSizeError",
        dom_exc_invalid_character_error => "InvalidCharacterError",
        dom_exc_in_use_attribute_error => "InUseAttributeError",
        dom_exc_not_supported_error => "NotSupportedError",
        dom_exc_invalid_node_type_error => "InvalidNodeTypeError",
    }

    "Headers (WHATWG Fetch §5.2)" {
        // Method and iteration-helper names.  `get` / `set` / `append` /
        // `value` / `key` already live elsewhere and are reused here.
        // `delete` is an ES keyword — field named `delete_str` to
        // sidestep the `r#delete` raw-identifier contortion.
        headers_global => "Headers",
        headers => "headers",
        delete_str => "delete",
        has => "has",
        get_set_cookie => "getSetCookie",
        for_each => "forEach",
        entries => "entries",
        keys => "keys",
        values => "values",
        set_cookie_header => "set-cookie",
    }

    "Request / Response (WHATWG Fetch §5.3 / §5.5)" {
        // Globals + IDL attr names + static factory method names +
        // enum strings.  `url` / `headers` already live above and are
        // reused here.
        request => "Request",
        response => "Response",
        method => "method",
        body => "body",
        body_used => "bodyUsed",
        ok => "ok",
        status_text => "statusText",
        redirected => "redirected",
        redirect => "redirect",
        mode => "mode",
        credentials => "credentials",
        cache => "cache",
        clone => "clone",
        json => "json",
        // Method / response-type string constants — pre-interned so
        // per-instance `.type` / `.method` accessor reads return the
        // pool entry directly.
        http_get => "GET",
        http_head => "HEAD",
        http_post => "POST",
        http_put => "PUT",
        http_delete => "DELETE",
        http_options => "OPTIONS",
        http_patch => "PATCH",
        http_connect => "CONNECT",
        http_trace => "TRACE",
        content_type => "content-type",
        application_json_utf8 => "application/json",
        text_plain_charset_utf8 => "text/plain;charset=UTF-8",
        response_type_default => "default",
        response_type_basic => "basic",
        response_type_cors => "cors",
        response_type_error => "error",
        response_type_opaque => "opaque",
        response_type_opaqueredirect => "opaqueredirect",
    }

    "ArrayBuffer / Blob / Body mixin (ES2020 §24.1 / File API §3 / WHATWG Fetch §5 Body mixin)" {
        // Constructor global names are separate fields from the
        // camelCase attribute / method names to sidestep the name
        // collision the Headers ctor ran into (`"Headers"` ctor name
        // vs `"headers"` attr name).
        array_buffer_global => "ArrayBuffer",
        blob_global => "Blob",
        byte_length => "byteLength",
        size => "size",
        slice => "slice",
        text => "text",
        array_buffer => "arrayBuffer",
    }

    "TypedArray + DataView (ES2024 §23.2 / §25.3)" {
        // Constructor name StringIds.  `data_view_global` and the 11
        // concrete-subclass entries back the real globals; the abstract
        // `%TypedArray%` intrinsic has no globalThis binding per
        // §23.2.2 so no StringId is needed for it.  All are interned
        // eagerly so `register_typed_array_subclass` can fetch them
        // without a per-call `strings.intern(...)` round-trip.
        data_view_global => "DataView",
        int8_array_global => "Int8Array",
        uint8_array_global => "Uint8Array",
        uint8_clamped_array_global => "Uint8ClampedArray",
        int16_array_global => "Int16Array",
        uint16_array_global => "Uint16Array",
        int32_array_global => "Int32Array",
        uint32_array_global => "Uint32Array",
        float32_array_global => "Float32Array",
        float64_array_global => "Float64Array",
        bigint64_array_global => "BigInt64Array",
        biguint64_array_global => "BigUint64Array",
        buffer => "buffer",
        byte_offset => "byteOffset",
        bytes_per_element => "BYTES_PER_ELEMENT",
    }

    "%TypedArray%.prototype method names" {
        // Pre-interned so `install_typed_array_prototype_members`
        // skips the per-method `strings.intern(...)` round-trip
        // during `Vm::new`.  `slice` / `set` / `values` / `keys` /
        // `entries` / `for_each` / `join` are reused from the
        // Headers / Body / Array sections above.
        fill => "fill",
        subarray => "subarray",
        copy_within => "copyWithin",
        reverse => "reverse",
        index_of => "indexOf",
        last_index_of => "lastIndexOf",
        includes => "includes",
        at => "at",
        every => "every",
        some => "some",
        find => "find",
        find_index => "findIndex",
        find_last => "findLast",
        find_last_index => "findLastIndex",
        map => "map",
        filter => "filter",
        reduce => "reduce",
        reduce_right => "reduceRight",
        sort => "sort",
        flat_map => "flatMap",
        to_locale_string => "toLocaleString",
    }

    "DataView.prototype method names" {
        // Pre-interned so `install_data_view_members` skips the
        // per-method `strings.intern(...)` round-trip during
        // `Vm::new`.  All 20 get* / set* names are unique to
        // DataView and have no overlap with reusable identifiers
        // above.
        get_int8 => "getInt8",
        get_uint8 => "getUint8",
        get_int16 => "getInt16",
        get_uint16 => "getUint16",
        get_int32 => "getInt32",
        get_uint32 => "getUint32",
        get_float32 => "getFloat32",
        get_float64 => "getFloat64",
        get_bigint64 => "getBigInt64",
        get_biguint64 => "getBigUint64",
        set_int8 => "setInt8",
        set_uint8 => "setUint8",
        set_int16 => "setInt16",
        set_uint16 => "setUint16",
        set_int32 => "setInt32",
        set_uint32 => "setUint32",
        set_float32 => "setFloat32",
        set_float64 => "setFloat64",
        set_bigint64 => "setBigInt64",
        set_biguint64 => "setBigUint64",
    }

    "TextEncoder / TextDecoder (WHATWG Encoding §8)" {
        // Constructor globals use the `*_global` suffix convention.
        // Method / attribute names are separate fields: `encoding`
        // doubles as the `TextDecoder.prototype.encoding` getter name
        // and an options-bag key, so the StringId is shared.
        text_encoder_global => "TextEncoder",
        text_decoder_global => "TextDecoder",
        encode => "encode",
        encode_into => "encodeInto",
        decode => "decode",
        encoding => "encoding",
        fatal => "fatal",
        ignore_bom => "ignoreBOM",
        read => "read",
        written => "written",
        stream => "stream",
        utf_8 => "utf-8",
        utf_16le => "utf-16le",
        utf_16be => "utf-16be",
    }

    "URLSearchParams / FormData (WHATWG URL §6 / XHR §4.3)" {
        // Constructor globals + method / accessor names that are
        // unique to these two interfaces.  `append` / `delete_str` /
        // `get` / `has` / `set` / `for_each` / `keys` / `values` /
        // `entries` / `sort` are reused from earlier sections.
        url_search_params_global => "URLSearchParams",
        form_data_global => "FormData",
        get_all => "getAll",
        to_string_method => "toString",
        application_form_urlencoded =>
            "application/x-www-form-urlencoded;charset=UTF-8",
        multipart_form_data_prefix => "multipart/form-data; boundary=",
        // Default filename used when a `Blob` (not a `File`) is appended
        // without an explicit filename argument — matches WHATWG XHR
        // §4.3 step "create an entry" and Chromium / Firefox behaviour.
        blob_default_filename => "blob",
    }

    "URL (WHATWG URL §6.1)" {
        // Constructor global + IDL accessor / static method names.
        // `origin` lives above (event-payload section) and is reused
        // here for `URL.prototype.origin`; `to_string_method` /
        // `to_json` are reused from the URLSearchParams / core
        // sections.  `search_params` is new in this section
        // (`"searchParams"` was not previously interned anywhere).
        // The `*_attr` suffix on `host_attr` / `port_attr` /
        // `search_attr` / `hash_attr` disambiguates the Rust field
        // name from potential future collisions with other
        // web-platform properties (CSS / HTML `host`, etc.) — same
        // naming precedent as `closed_attr` / `locked_attr` in the
        // streams section.  The literal string values match the
        // WebIDL identifiers verbatim.
        url_global => "URL",
        href => "href",
        protocol => "protocol",
        host_attr => "host",
        hostname => "hostname",
        port_attr => "port",
        pathname => "pathname",
        search_attr => "search",
        hash_attr => "hash",
        username => "username",
        password => "password",
        search_params => "searchParams",
        can_parse => "canParse",
        parse_url => "parse",
    }

    "HTML form-control prototypes (slot #11-tags-T1-v2 / HTML §4.10)" {
        // Constructor globals for the 10 per-tag prototypes + 2 live
        // collection prototypes + ValidityState exposure.  See
        // `m4-12-pr-tags-t1-v2-plan.md` §F for the prototype install
        // ordering rationale.
        html_label_global => "HTMLLabelElement",
        html_optgroup_global => "HTMLOptGroupElement",
        html_legend_global => "HTMLLegendElement",
        html_option_global => "HTMLOptionElement",
        html_fieldset_global => "HTMLFieldSetElement",
        html_form_global => "HTMLFormElement",
        html_button_global => "HTMLButtonElement",
        html_textarea_global => "HTMLTextAreaElement",
        html_select_global => "HTMLSelectElement",
        html_input_global => "HTMLInputElement",
        html_form_controls_collection_global => "HTMLFormControlsCollection",
        html_options_collection_global => "HTMLOptionsCollection",
        validity_state_global => "ValidityState",
        // IDL accessor names — DOMString reflect / boolean reflect /
        // enumerated keyword.  Some short, ambiguous names like
        // `"type"` and `"select"` are interned more than once under
        // different field names (`event_type` / `type_attr` for
        // `"type"`, `select_method` for `"select"`) so that each
        // call site gets a self-documenting `well_known.<field>`
        // accessor — the runtime intern table deduplicates so all
        // these field aliases resolve to the same `StringId`.  This
        // block introduces the IDL-side aliases for names that
        // already exist as event / DOM-API fields above; the
        // duplication is a readability choice, not a runtime cost.
        // (`options` is defined below in the `<select>` IDL block
        // because it landed in this PR alongside the select/option
        // surface — see that location for the form-control IDL
        // members.)
        html_for => "htmlFor",
        for_attr => "for",
        control => "control",
        form_attr => "form",
        disabled => "disabled",
        label_attr => "label",
        // `<option>` IDL members.
        default_selected => "defaultSelected",
        selected => "selected",
        // `<fieldset>` / form-association.
        elements_attr => "elements",
        // `<form>` IDL members.
        action => "action",
        method_attr => "method",
        enctype => "enctype",
        accept_charset => "acceptCharset",
        no_validate => "noValidate",
        autocomplete => "autocomplete",
        rel => "rel",
        rel_list => "relList",
        submit_method => "submit",
        request_submit => "requestSubmit",
        reset_method => "reset",
        // ValidityState + ConstraintValidation members.
        validity => "validity",
        validation_message => "validationMessage",
        will_validate => "willValidate",
        check_validity => "checkValidity",
        report_validity => "reportValidity",
        set_custom_validity => "setCustomValidity",
        value_missing => "valueMissing",
        type_mismatch => "typeMismatch",
        pattern_mismatch => "patternMismatch",
        too_short => "tooShort",
        too_long => "tooLong",
        range_underflow => "rangeUnderflow",
        range_overflow => "rangeOverflow",
        step_mismatch => "stepMismatch",
        bad_input => "badInput",
        custom_error => "customError",
        valid_attr => "valid",
        // `<button>` / `<input>` button-type.
        type_attr => "type",
        // `<input>` IDL members.
        accept => "accept",
        alt => "alt",
        checked_attr => "checked",
        default_checked => "defaultChecked",
        default_value => "defaultValue",
        dir_name => "dirName",
        files => "files",
        form_action => "formAction",
        form_enctype => "formEnctype",
        form_method => "formMethod",
        form_no_validate => "formNoValidate",
        form_target => "formTarget",
        indeterminate => "indeterminate",
        list_attr => "list",
        max => "max",
        max_length => "maxLength",
        min => "min",
        min_length => "minLength",
        multiple => "multiple",
        pattern => "pattern",
        placeholder => "placeholder",
        read_only => "readOnly",
        required => "required",
        size_attr => "size",
        step => "step",
        value_as_date => "valueAsDate",
        value_as_number => "valueAsNumber",
        labels => "labels",
        select_method => "select",
        set_selection_range => "setSelectionRange",
        set_range_text => "setRangeText",
        selection_start => "selectionStart",
        selection_end => "selectionEnd",
        selection_direction => "selectionDirection",
        step_up => "stepUp",
        step_down => "stepDown",
        show_picker => "showPicker",
        // `<textarea>` IDL members.
        rows => "rows",
        cols => "cols",
        wrap => "wrap",
        text_length => "textLength",
        // `<select>` IDL members.
        selected_index => "selectedIndex",
        selected_options => "selectedOptions",
        options => "options",
        named_anchor => "named", // legacy; reserved
        // SelectionDirection enum strings.
        selection_dir_none => "none",
        selection_dir_forward => "forward",
        selection_dir_backward => "backward",
        // `<input>` type keyword (default).
        input_type_text => "text",
        // Form-method enum strings.
        method_get => "get",
        method_post => "post",
        method_dialog => "dialog",
        // Form-enctype enum strings.
        enctype_urlencoded_lower => "application/x-www-form-urlencoded",
        enctype_multipart => "multipart/form-data",
        enctype_text_plain => "text/plain",
        // `reset` event name (HTML §4.10.21.3).
        reset_event => "reset",
        // `invalid` event name (HTML §4.10.20.4).  Fired by
        // `checkValidity()` / `reportValidity()` when constraint
        // validation rejects a candidate control.
        invalid_event => "invalid",
    }

    "Range / StaticRange / Traversal (slot #11-traversal-and-range-pr-a2-bindings)" {
        // Constructor globals (WHATWG DOM §4.4 / §4.5 / §6.1 / §6.3 / §6.4).
        range_global => "Range",
        static_range_global => "StaticRange",
        tree_walker_global => "TreeWalker",
        node_iterator_global => "NodeIterator",
        node_filter_global => "NodeFilter",
        // Accessor / method names.  `cancel` / `close` / `start` are
        // pre-interned in earlier sections and reused.
        start_container => "startContainer",
        start_offset => "startOffset",
        end_container => "endContainer",
        end_offset => "endOffset",
        common_ancestor_container => "commonAncestorContainer",
        collapsed_attr => "collapsed",
        set_start_method => "setStart",
        set_end_method => "setEnd",
        set_start_before_method => "setStartBefore",
        set_start_after_method => "setStartAfter",
        set_end_before_method => "setEndBefore",
        set_end_after_method => "setEndAfter",
        select_node_method => "selectNode",
        select_node_contents_method => "selectNodeContents",
        collapse_method => "collapse",
        clone_range_method => "cloneRange",
        clone_contents_method => "cloneContents",
        extract_contents_method => "extractContents",
        delete_contents_method => "deleteContents",
        insert_node_method => "insertNode",
        surround_contents_method => "surroundContents",
        compare_boundary_points_method => "compareBoundaryPoints",
        compare_point_method => "comparePoint",
        is_point_in_range_method => "isPointInRange",
        intersects_node_method => "intersectsNode",
        detach_method => "detach",
        create_contextual_fragment_method => "createContextualFragment",
        // Range compareBoundaryPoints constants.
        start_to_start => "START_TO_START",
        start_to_end => "START_TO_END",
        end_to_end => "END_TO_END",
        end_to_start => "END_TO_START",
        // Traversal (§6.1 / §6.4) accessors + methods.
        what_to_show => "whatToShow",
        filter_attr => "filter",
        current_node => "currentNode",
        reference_node => "referenceNode",
        pointer_before_reference_node => "pointerBeforeReferenceNode",
        parent_node_method => "parentNode",
        first_child_method => "firstChild",
        last_child_method => "lastChild",
        next_sibling_method => "nextSibling",
        previous_sibling_method => "previousSibling",
        next_node_method => "nextNode",
        previous_node_method => "previousNode",
        accept_node_method => "acceptNode",
        // NodeFilter constants (WHATWG DOM §6.3).
        filter_accept => "FILTER_ACCEPT",
        filter_reject => "FILTER_REJECT",
        filter_skip => "FILTER_SKIP",
        show_all_const => "SHOW_ALL",
        show_element_const => "SHOW_ELEMENT",
        show_attribute_const => "SHOW_ATTRIBUTE",
        show_text_const => "SHOW_TEXT",
        show_cdata_section_const => "SHOW_CDATA_SECTION",
        show_entity_reference_const => "SHOW_ENTITY_REFERENCE",
        show_entity_const => "SHOW_ENTITY",
        show_processing_instruction_const => "SHOW_PROCESSING_INSTRUCTION",
        show_comment_const => "SHOW_COMMENT",
        show_document_const => "SHOW_DOCUMENT",
        show_document_type_const => "SHOW_DOCUMENT_TYPE",
        show_document_fragment_const => "SHOW_DOCUMENT_FRAGMENT",
        show_notation_const => "SHOW_NOTATION",
        // document.createRange / createTreeWalker / createNodeIterator.
        create_range_method => "createRange",
        create_tree_walker_method => "createTreeWalker",
        create_node_iterator_method => "createNodeIterator",
    }

    "Selection (Selection API §3, slot #11-traversal-and-range-pr-b-selection)" {
        selection_global => "Selection",
        get_selection_method => "getSelection",
        // Accessor names.
        anchor_node_attr => "anchorNode",
        anchor_offset_attr => "anchorOffset",
        focus_node_attr => "focusNode",
        focus_offset_attr => "focusOffset",
        is_collapsed_attr => "isCollapsed",
        range_count_attr => "rangeCount",
        direction_attr => "direction",
        // Method names.  `collapse` + `type` + `toString` already
        // pre-interned (in Range / Form / Event sections); reused here.
        get_range_at_method => "getRangeAt",
        add_range_method => "addRange",
        remove_range_method => "removeRange",
        remove_all_ranges_method => "removeAllRanges",
        empty_method => "empty",
        set_position_method => "setPosition",
        collapse_to_start_method => "collapseToStart",
        collapse_to_end_method => "collapseToEnd",
        extend_method => "extend",
        set_base_and_extent_method => "setBaseAndExtent",
        select_all_children_method => "selectAllChildren",
        delete_from_document_method => "deleteFromDocument",
        contains_node_method => "containsNode",
        // SelectionType / direction enum strings (Selection API §3.1).
        selection_type_none => "None",
        selection_type_caret => "Caret",
        selection_type_range => "Range",
        selection_dir_directionless => "directionless",
        // `selectionchange` event name (Selection API §3.4 +
        // HTML §8.1.4.2 "selection task source").
        selectionchange_event => "selectionchange",
    }

    "File API (slot #11-file-api)" {
        // Constructor globals.  `Blob` ctor itself lives in the
        // ArrayBuffer / Blob section above.
        file_global => "File",
        file_list_global => "FileList",
        file_reader_global => "FileReader",
        // `File` IDL members beyond what Blob provides.
        last_modified => "lastModified",
        // Blob ctor options dict keys (`type` lives elsewhere as
        // `r#type` / `event_type` / `type_attr` — semantically the
        // same StringId via dedup; we use `event_type` at File ctor
        // sites since the literal is `"type"`).
        endings => "endings",
        endings_transparent => "transparent",
        endings_native => "native",
        // `FileReader` IDL members.  `error` already lives in core
        // (line 100); `abort` / `onabort` already exist in the
        // AbortController section and are reused.  Result enum is just
        // values, not names.
        ready_state => "readyState",
        result_attr => "result",
        read_as_text => "readAsText",
        read_as_array_buffer => "readAsArrayBuffer",
        read_as_data_url => "readAsDataURL",
        read_as_binary_string => "readAsBinaryString",
        // `FileReader` event handler attribute names.  `onabort`
        // already exists (AbortController section); `onload` /
        // `onloadstart` / `onloadend` / `onprogress` / `onerror` are
        // newly added here.
        onload => "onload",
        onloadstart => "onloadstart",
        onloadend => "onloadend",
        onprogress => "onprogress",
        onerror => "onerror",
        // Event type names fired by FileReader (per FileAPI §6.5).
        // `error` is shared with the core throw-error name.
        load_event_type => "load",
        loadstart_event_type => "loadstart",
        loadend_event_type => "loadend",
        progress_event_type => "progress",
        // FileReader.readyState constant names installed on the
        // constructor + prototype per FileAPI §6.
        empty_const => "EMPTY",
        loading_const => "LOADING",
        done_const => "DONE",
    }

    "Crypto / SubtleCrypto (WebCrypto §10 / §14)" {
        // `window.crypto` accessor identifier + the 2 constructor
        // globals (`Crypto` / `SubtleCrypto`) — `new Crypto()` and
        // `new SubtleCrypto()` both throw "Illegal constructor".
        // `getRandomValues` / `randomUUID` are methods on
        // `Crypto.prototype`; `subtle` is an accessor on
        // `Crypto.prototype` returning the `SubtleCrypto`
        // `[SameObject]` singleton; `digest` is a method on
        // `SubtleCrypto.prototype`.  Canonical algorithm names
        // (`SHA-1` / `SHA-256` / `SHA-384` / `SHA-512`) are
        // compared at call time via `eq_ignore_ascii_case` rather
        // than pre-interned — `SubtleCrypto.digest` callers rarely
        // pass canonical-case literals (libraries spell `'sha-256'`
        // or `'SHA-256'` interchangeably) so a StringId equality
        // fast path would miss most hits.
        crypto_accessor => "crypto",
        crypto_global => "Crypto",
        subtle_crypto_global => "SubtleCrypto",
        get_random_values => "getRandomValues",
        random_uuid => "randomUUID",
        subtle => "subtle",
        digest => "digest",
    }

    "ReadableStream (WHATWG Streams §4)" {
        // Constructor globals + method / accessor names unique to
        // the streams surface.  `read` / `value` / `done` /
        // `reason` / `size` / `stream` / `byte_length` already
        // live above and are reused here; `cancel` is introduced
        // in this section because it has no prior call site outside
        // the streams API.
        readable_stream_global => "ReadableStream",
        readable_stream_default_reader_global => "ReadableStreamDefaultReader",
        readable_stream_default_controller_global =>
            "ReadableStreamDefaultController",
        count_queuing_strategy_global => "CountQueuingStrategy",
        byte_length_queuing_strategy_global => "ByteLengthQueuingStrategy",
        start => "start",
        pull => "pull",
        cancel => "cancel",
        high_water_mark => "highWaterMark",
        get_reader => "getReader",
        release_lock => "releaseLock",
        desired_size => "desiredSize",
        enqueue => "enqueue",
        close => "close",
        locked_attr => "locked",
        closed_attr => "closed",
    }
}

/// Well-known symbol IDs, allocated at VM creation.
#[allow(dead_code)]
pub(crate) struct WellKnownSymbols {
    pub(crate) iterator: SymbolId,
    pub(crate) async_iterator: SymbolId,
    pub(crate) has_instance: SymbolId,
    pub(crate) to_primitive: SymbolId,
    pub(crate) to_string_tag: SymbolId,
    pub(crate) species: SymbolId,
    pub(crate) is_concat_spreadable: SymbolId,
}

impl WellKnownSymbols {
    /// Allocate the 7 well-known Symbol records at fixed SymbolIds 0-6
    /// and return the populated table alongside the symbol Vec (which
    /// the caller stores on `VmInner.symbols`).  Returning the Vec
    /// avoids a second `SymbolId` round-trip during VM construction —
    /// the caller moves it straight into the field.
    pub(crate) fn alloc_all(strings: &mut StringPool) -> (Self, Vec<SymbolRecord>) {
        let mut symbols = Vec::new();
        let mut alloc = |desc: &str| -> SymbolId {
            let id = SymbolId(symbols.len() as u32);
            symbols.push(SymbolRecord {
                description: Some(strings.intern(desc)),
            });
            id
        };
        let well_known = Self {
            iterator: alloc("Symbol.iterator"),
            async_iterator: alloc("Symbol.asyncIterator"),
            has_instance: alloc("Symbol.hasInstance"),
            to_primitive: alloc("Symbol.toPrimitive"),
            to_string_tag: alloc("Symbol.toStringTag"),
            species: alloc("Symbol.species"),
            is_concat_spreadable: alloc("Symbol.isConcatSpreadable"),
        };
        (well_known, symbols)
    }
}
